
# **Tasca S10.01. APIs REST**

Aplicaràs el que has après sobre APIs REST, mètodes HTTP i codis d'estat, utilitzant APIs públiques per consultar dades, filtrar-les i finalment desar-les en un DataFrame de pandas..

# **📚 Llibreries**

In [75]:
import requests # llibreria per fer peticions a internet
import json # llibreria per processar i interpretar text en format JSON
import pandas as pd # llibreria per processar dades

# **♻ Re-utilització de funcions:**

In [76]:
def mostrar_dataframe(df, títol):
#Presenta les dades en format tabular amb el títol indicat

    # Mostrem títol
    print("\n" + "="*100)
    print(títol)
    print("="*100)
    # La funció display mostra les dades del dataframe en format taula.
    display(df)

# **Nivell 1: Exploració bàsica amb una API de laboratori.**

Des d’un Jupyter Notebook faràs els següents exercicis utilitzant la llibreria requests de Python.

Exploració bàsica amb una API de laboratori.
1. Consulta l’API pública JSONPlaceholder utilitzant el mètode GET per obtenir:
    *   Llista de publicacions (/posts)
    *   Llista d’usuaris (/users)
    *   Llista de tasques (/todos)

2. Mostra per pantalla:
    *   La quantitat total de cada recurs.
    *   El codi d'estat de cada petició.

3. Fes una petició a una publicació inexistent per obtenir un error 404 i mostra el codi d'estat rebut.

4. Fes una petició POST per crear una nova publicació fictícia. Inclou el títol, el cos del missatge i un userId.
    *   Mostra la resposta JSON.
    *   Mostra el codi d'estat.

5. Fes una petició PATCH per modificar parcialment una publicació existent.
    *   Mostra la resposta JSON.
    *   Mostra el codi d'estat.

6. Fes una petició DELETE sobre una publicació.
    *   Mostra la resposta JSON.
    *   Mostra el codi d'estat.

# **Disseny i implementació de la solució**

### ***A. Mètode GET***

1. Consulta l’API pública JSONPlaceholder utilitzant el mètode GET per obtenir:
    *   Llista de publicacions (/posts)
    *   Llista d’usuaris (/users)
    *   Llista de tasques (/todos)

2. Mostra per pantalla:
    *   La quantitat total de cada recurs.
    *   El codi d'estat de cada petició.

In [77]:
# DEFINICIÓ DE LA FUNCIÓ

def obtenir_dades (url, text):
# Envia una petició GET a la URL indicada per obtenir-ne el contingut.
# El resultat (la resposta del servidor) es desa a la variable resposta
  print (text)
  resposta = requests.get(url)
  print("Hem obtingut",len(resposta.json()),"dades")
  print ("El codi d'estat de la petició és:", resposta.status_code," -", resposta.reason)
  return resposta.json()

# DADES
url_posts = "https://jsonplaceholder.typicode.com/posts"
url_usuaris = "https://jsonplaceholder.typicode.com/users"
url_tasques = "https://jsonplaceholder.typicode.com/todos"


# EXECUCIÓ
llista_publicacions = obtenir_dades (url_posts, "LLISTA DE PUBLICACIONS")
llista_usuaris = obtenir_dades (url_usuaris, "LLISTA D'USUARIS")
llista_tasques = obtenir_dades (url_tasques, "LLISTA DE TASQUES")

LLISTA DE PUBLICACIONS
Hem obtingut 100 dades
El codi d'estat de la petició és: 200  - OK
LLISTA D'USUARIS
Hem obtingut 10 dades
El codi d'estat de la petició és: 200  - OK
LLISTA DE TASQUES
Hem obtingut 200 dades
El codi d'estat de la petició és: 200  - OK

3. Fes una petició a una publicació inexistent per obtenir un error 404 i mostra el codi d'estat rebut.

In [78]:
# DADES
url_novalida = "https://jsonplaceholder.typicode.com/publicacions"

# EXECUCIÓ
obtenir_dades (url_novalida, "PUBLICACIÓ INEXISTENT")

PUBLICACIÓ INEXISTENT
Hem obtingut 0 dades
El codi d'estat de la petició és: 404  - Not Found

{}

### ***B. Mètode POST***

4. Fes una petició POST per crear una nova publicació fictícia. Inclou el títol, el cos del missatge i un userId.
    *   Mostra la resposta JSON.
    *   Mostra el codi d'estat.

In [79]:
# DEFINICIÓ DE LA FUNCIÓ

def enviar_dades (url, dades):
  print ("ENVIAMENT DE DADES")
  resposta = requests.post(url, dades)
  print ("La resposta JSON és:", resposta.json())
  print ("El codi d'estat de la petició és:", resposta.status_code," -", resposta.reason)


# DADES
dades = {"userId": 99, "title": "Prova55", "body": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit"}

# EXECUCIÓ
enviar_dades (url_posts, dades)

ENVIAMENT DE DADES
La resposta JSON és: {'userId': '99', 'title': 'Prova55', 'body': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'id': 101}
El codi d'estat de la petició és: 201  - Created

### ***C. Mètode PATCH***

5. Fes una petició PATCH per modificar parcialment una publicació existent.
    *   Mostra la resposta JSON.
    *   Mostra el codi d'estat.

In [80]:
# DEFINICIÓ DE LA FUNCIÓ

def modificar_dades (url, dades):
  print ("MODIFICACIÓ DE DADES")
  resposta = requests.patch(url, json=dades)
  print ("La resposta JSON és:", resposta.json())
  print ("El codi d'estat de la petició és:", resposta.status_code," -", resposta.reason)


# DADES
# Modifiquem el post 1 afegint el seu ID a la URL
url_patch = "https://jsonplaceholder.typicode.com/posts/1"
dades = {"title": "Prova66", "body": "Hola"}

# EXECUCIÓ
modificar_dades (url_patch, dades)

MODIFICACIÓ DE DADES
La resposta JSON és: {'userId': 1, 'id': 1, 'title': 'Prova66', 'body': 'Hola'}
El codi d'estat de la petició és: 200  - OK

### ***D. Mètode DELETE***

6. Fes una petició DELETE sobre una publicació.
    *   Mostra la resposta JSON.
    *   Mostra el codi d'estat.

In [81]:
# DEFINICIÓ DE LA FUNCIÓ

def esborrar_dades (url):
  print ("ELIMINACIÓ DE DADES")
  resposta = requests.delete(url)
  print ("La resposta JSON és:", resposta.json())
  print ("El codi d'estat de la petició és:", resposta.status_code," -", resposta.reason)


# DADES
# Esborrem  el post 1 afegint el seu ID a la URL
url_del = "https://jsonplaceholder.typicode.com/posts/1"

# EXECUCIÓ
esborrar_dades (url_del)

ELIMINACIÓ DE DADES
La resposta JSON és: {}
El codi d'estat de la petició és: 200  - OK

# **Nivell 2: Interacció amb una API pública real**

1. Explora el repositori de Public APIs i tria una API que permeti fer peticions GET.

2. Llegeix la documentació de l'API:

    *   Revisa la secció d’endpoints disponibles. En un markdown, apunta com a mínim dos endpoints diferents.
    *   Comprova si ofereix filtres o paràmetres opcionals interessants. En un markdown, anota’ls.
    *   Verifica que la resposta sigui en format JSON (és el més adequat per a aquest exercici).

3. Fes una petició GET senzilla:
    *   Mostra el codi d'estat de la resposta.
    *   Imprimeix de forma clara alguns dels camps de la resposta JSON.

4. Converteix les dades a un DataFrame de pandas:
    *   Mostra les primeres files del DataFrame.

# **Disseny i implementació de la solució**

Treballarem amb la següent API:
Exchangerate.host API

Ens permet obtenir els canvis de moneda actuals i històrics.

La URL base és: https://api.exchangerate.host/

Endpoints:

*   /live: per obtenir el canvi més recent
*   /historical: retorna canvi a una data determinada
*   /convert: converteix un import d'una moneda a una altra
*   /timeframe: per obtenir canvi entre dues dates
*   /change: per obtenir les fluctuacions del canvi
*   /list: per obtenir llista de monedes

Tots els endpoints retornen dades estructurades en format JSON.

In [82]:
# Utilitzem Frankfurter API, que és 100% gratuïta i no necessita access_key
url_canvi = "https://api.frankfurter.app/latest?from=USD&to=EUR"

resposta_json = obtenir_dades(url_canvi, "CANVI ACTUAL DE USD A EUR")
print("Moneda base:", resposta_json['base'])
print("Data:", resposta_json['date'])
print("Canvi a moneda destí:", resposta_json['rates'])

CANVI ACTUAL DE USD A EUR
Hem obtingut 4 dades
El codi d'estat de la petició és: 200  - OK
Moneda base: USD
Data: 2026-10-08
Canvi a moneda destí: {'EUR': 0.89397}

In [90]:

url_divises = "https://api.frankfurter.dev/v2/currencies"
json_divises = obtenir_dades(url_divises, "LECTURA DE DIVISES")
df_divises = pd.DataFrame(json_divises)
mostrar_dataframe(df_divises.head(),"LLISTA DE DIVISES")

LECTURA DE DIVISES
Hem obtingut 165 dades
El codi d'estat de la petició és: 200  - OK

====================================================================================================
LLISTA DE DIVISES
====================================================================================================

,iso_code,iso_numeric,name,symbol,start_date,end_date
0,AED,784,United Arab Emirates Dirham,د.إ,1996-04-11,2026-10-09
1,AFN,971,Afghan Afghani,؋,2003-01-07,2026-10-09
2,ALL,008,Albanian Lek,L,1998-07-07,2026-10-09
3,AMD,051,Armenian Dram,֏,1994-03-18,2026-10-09
4,ANG,532,Netherlands Antillean Guilder,ƒ,1971-12-18,2026-10-09

# **Nivell 3: API d'Open Data Barcelona**

1. Utilitza l’API d’Open Data BCN per:
      *   Cercar un dataset del teu interès mitjançant package_search i package_show.

2. Dels resultats obtinguts, selecciona’n un que tingui recursos disponibles en CSV o JSON.


3. Amb el resource_id del recurs seleccionat, realitza una consulta mitjançant datastore_search per:
      *   Recuperar almenys 100 registres.

4. Converteix els resultats a un DataFrame.


5. Desa el DataFrame en un fitxer .csv.

# **Disseny i implementació de la solució**

**API de gestió del catàleg**

*   url base: https://opendata-ajuntament.barcelona.cat/data/api/action/mètode
*   url per accedir-hi: https://opendata-ajuntament.barcelona.cat/data/api/action/mètode

Aquests **mètodes** són públics i no requereixen cap tipus d'identificació ni token sent alguns exemples:


*   **current_package_list_with_resources**: retorna el llistat de datasets actuals i els seus recursos
*   **package_search**: fa una cerca dins del catàleg de datasets
*   **resource_show**: retorna les metadades del dataset a partir de l'id del dataset i entre elles el resource_id dels recursos
*   **datastore_search**: retorna la informació de cada recurs.

Exemples:

https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_show?id=arbrat-zona

https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search?resource_id=f7134b6f-95ce-4b83-bacd-6f411bd9c1f0

Si a més volguéssim buscar, per exemple, el valor=14 dins el recurs:

https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search?resource_id=f7134b6f-95ce-4b83-bacd-6f411bd9c1f0&q=14

In [100]:
url_bcn = "https://opendata-ajuntament.barcelona.cat/data/api/action/current_package_list_with_resources"
cataleg = requests.get(url_bcn)
print(cataleg.json())

{'help': 'https://opendata-ajuntament.barcelona.cat/data/api/3/action/help_show?name=current_package_list_with_resources', 'success': True, 'result': [{'notes_translated': {'ca': 'Superfície (m²) de les propietats immobiliàries transmeses per compravenda a la ciutat de Barcelona per tipologia d’ús de l’immoble durant el període especificat segons els registres notarials. Es considera la superfície consignada a l’escriptura. En cas d’informació dubtosa, s’utilitza la superfície associada a la referència cadastral de l’immoble inscrit en l’acte de compravenda.', 'en': 'Surface area (m²) of real estate properties transmitted by sale in the city of Barcelona by property use during the specified period based on notarial records. The surface area stated in the deed is considered. In case of uncertain information, the surface associated with the cadastral reference of the property registered in the sale deed is used.', 'es': 'Superficie (m²) de las propiedades inmobiliarias transmitidas por compraventa en la ciudad de Barcelona por tipología de uso del inmueble durante el período especificado según los registros notariales. Se considera la superficie consignada en la escritura. En caso de información dudosa, se utiliza la superficie asociada a la referencia catastral del inmueble inscrito en el acto de compraventa.'}, 'geolocation': 'No', 'dades_alt_valor': 'No', 'url_tornada': {'ca': '', 'en': '', 'es': ''}, 'dataset_fields_description': '__NOTA:__ Els recursos dels darrers anys poden estar subjectes a lleugeres revisions o modificacions a causa de la naturalesa del procés de digitalització de les escriptures notarials.', 'fuente': 'Registres notarials de les compravendes de propietats immobiliàries de Barcelona', 'tag': 'Any 2026,Any 2025,Any 2024,Any 2023,Any 2022,Any 2021,Any 2020,Any 2019,Any 2018,Any 2017,Any 2016,Any 2015,Any 2014,Any 2013,Any 2012,Transmissions compravenda,Notaris', 'private': False, 'num_tags': 17, 'code': 'notaris_compravendes_trans_tip_us_sup', 'frequency': 'MENSUAL', 'id': 'd6846542-7785-49ad-8dd4-03a608abb644', 'title_translated': {'ca': 'Superficie (m²) de les propietats immobiliàries transmeses per compravenda, segons els registres notarials, per tipologia d’ús de l’immoble', 'en': 'Area (m²) of real estate properties transmitted by sale transaction, based on notarials records, by property use', 'es': 'Superficie (m2) de las propiedades inmobiliarias transmitidas por compraventa, según los registros notariales, por tipología de uso de la propiedad'}, 'metadata_modified': '2026-04-29T10:19:11.677486', 'author': 'Gerència Municipal', 'author_email': None, 'isopen': True, 'long_format': 'Yes', 'state': 'active', 'version': '', 'mar_od': 'Yes', 'relationships_as_object': [], 'department': 'Oficina Municipal de Dades', 'creator_user_id': '50d6b44b-a141-4dc6-b663-5deb4ab0dd63', 'type': 'dataset', 'resources': [{'api_access_number_absolute': '564', 'cache_last_updated': None, 'incorporated_in_cityos_res': 'No', 'token_type': '', 'package_id': 'd6846542-7785-49ad-8dd4-03a608abb644', 'datastore_active': True, 'id': 'f00c112c-6512-4d83-bb63-48a0627ebc03', 'description': '', 'state': 'active', 'api_access_number': '88', 'size': '30671', 'token_required': 'No', 'hash': '', 'token_name': '', 'format': 'CSV', 'downloads': '334', 'mimetype_inner': None, 'url_type': 'upload', 'token_provider': '', 'column_types': '[Integer, Integer, Integer, String, Integer, String, Integer, String, String]', 'hide_url': 'No', 'token_version': '', 'mimetype': None, 'cache_url': None, 'name': '2026_notaris_compravendes_trans_tip_us_sup.csv', 'created': '2026-03-20T09:04:06.709264', 'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d6846542-7785-49ad-8dd4-03a608abb644/resource/f00c112c-6512-4d83-bb63-48a0627ebc03/download', 'downloads_absolute': '429', 'map_visualization_res': 'none', 'qa': '{\'updated\': \'2026-10-09T02:09:27.292150\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2026-03-21T02:10:16.917343\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}', 'last_modified': '2026-04-29T12:19:11.595527', 'position': 0, 'revision_id': 'c0d6e357-7e5f-4f5f-a45d-c71eee72858a', 'resource_type': None}, {'api_access_number_absolute': '105', 'cache_last_updated': None, 'incorporated_in_cityos_res': 'No', 'token_type': '', 'package_id': 'd6846542-7785-49ad-8dd4-03a608abb644', 'datastore_active': True, 'id': 'be8f7e31-7154-4f80-b481-69dee1acd392', 'description': '', 'state': 'active', 'api_access_number': '55', 'size': '186788', 'token_required': 'No', 'hash': '', 'token_name': '', 'format': 'CSV', 'downloads': '221', 'mimetype_inner': None, 'url_type': 'upload', 'token_provider': '', 'column_types': '[Integer, Integer, Integer, String, Integer, String, Integer, String, String]', 'hide_url': 'No', 'token_version': '', 'mimetype': None, 'cache_url': None, 'name': '2025_notaris_compravendes_trans_tip_us_sup.csv', 'created': '2026-03-20T10:41:25.945265', 'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d6846542-7785-49ad-8dd4-03a608abb644/resource/be8f7e31-7154-4f80-b481-69dee1acd392/download', 'downloads_absolute': '299', 'map_visualization_res': 'none', 'qa': '{\'updated\': \'2026-10-09T02:09:27.303358\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2026-03-21T02:10:16.937348\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}', 'last_modified': '2026-04-29T12:18:35.069069', 'position': 1, 'revision_id': 'c0d6e357-7e5f-4f5f-a45d-c71eee72858a', 'resource_type': None}, {'api_access_number_absolute': '97', 'cache_last_updated': None, 'incorporated_in_cityos_res': 'No', 'token_type': '', 'package_id': 'd6846542-7785-49ad-8dd4-03a608abb644', 'datastore_active': True, 'id': 'e65872ac-531a-4b80-990b-fd7e38e4ef9c', 'description': '', 'state': 'active', 'api_access_number': '47', 'size': '186812', 'token_required': 'No', 'hash': '', 'token_name': '', 'format': 'CSV', 'downloads': '185', 'mimetype_inner': None, 'url_type': 'upload', 'token_provider': '', 'column_types': '[Integer, Integer, Integer, String, Integer, String, Integer, String, String]', 'hide_url': 'No', 'token_version': '', 'mimetype': None, 'cache_url': None, 'name': '2024_notaris_compravendes_trans_tip_us_sup.csv', 'created': '2026-03-20T10:42:48.796544', 'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d6846542-7785-49ad-8dd4-03a608abb644/resource/e65872ac-531a-4b80-990b-fd7e38e4ef9c/download', 'downloads_absolute': '261', 'map_visualization_res': 'none', 'qa': '{\'updated\': \'2026-10-09T02:09:27.312920\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2026-03-21T02:10:16.958871\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}', 'last_modified': '2026-04-29T12:17:52.817721', 'position': 2, 'revision_id': 'c0d6e357-7e5f-4f5f-a45d-c71eee72858a', 'resource_type': None}, {'api_access_number_absolute': '96', 'cache_last_updated': None, 'incorporated_in_cityos_res': 'No', 'token_type': '', 'package_id': 'd6846542-7785-49ad-8dd4-03a608abb644', 'datastore_active': True, 'id': 'e92b5aff-4d30-4372-86c5-88e14f7b8f50', 'description': '', 'state': 'active', 'api_access_number': '47', 'size': '173901', 'token_required': 'No', 'hash': '', 'token_name': '', 'format': 'CSV', 'downloads': '163', 'mimetype_inner': None, 'url_type': 'upload', 'token_provider': '', 'column_types': '[Integer, Integer, Integer, String, Integer, String, Integer, String, String]', 'hide_url': 'No', 'token_version': '', 'mimetype': None, 'cache_url': None, 'name': '2023_notaris_compravendes_trans_tip_us_sup.csv', 'created': '2026-03-20T10:44:11.790715', 'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d6846542-7785-49ad-8dd4-03a608abb644/resource/e92b5aff-4d30-4372-86c5-88e14f7b8f50/download', 'downloads_absolute': '210', 'map_visualization_res': 'none', 'qa': '{\'updated\': \'2026-10-09T02:09:27.326398\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2026-03-21T02:10:16.981513\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}', 'last_modified': '2026-04-29T12:17:05.998673', 'position': 3, 'revision_id': 'c0d6e357-7e5f-4f5f-a45d-c71eee72858a', 'resource_type': None}, {'api_access_number_absolute': '90', 'cache_last_updated': None, 'incorporated_in_cityos_res': 'No', 'token_type': '', 'package_id': 'd6846542-7785-49ad-8dd4-03a608abb644', 'datastore_active': True, 'id': 'e84e3611-cbe9-43e6-9bea-901b71173b48', 'description': '', 'state': 'active', 'api_access_number': '45', 'size': '184505', 'token_required': 'No', 'hash': '', 'token_name': '', 'format': 'CSV', 'downloads': '154', 'mimetype_inner': None, 'url_type': 'upload', 'token_provider': '', 'column_types': '[Integer, Integer, Integer, String, Integer, String, Integer, String, String]', 'hide_url': 'No', 'token_version': '', 'mimetype': None, 'cache_url': None, 'name': '2022_notaris_compravendes_trans_tip_us_sup.csv', 'created': '2026-03-20T10:45:34.936358', 'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d6846542-7785-49ad-8dd4-03a608abb644/resource/e84e3611-cbe9-43e6-9bea-901b71173b48/download', 'downloads_absolute': '199', 'map_visualization_res': 'none', 'qa': '{\'updated\': \'2026-10-09T02:09:27.336010\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2026-03-21T02:10:17.006204\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}', 'last_modified': '2026-04-29T12:16:10.229660', 'position': 4, 'revision_id': 'c0d6e357-7e5f-4f5f-a45d-c71eee72858a', 'resource_type': None}, {'api_access_number_absolute': '86', 'cache_last_updated': None, 'incorporated_in_cityos_res': 'No', 'token_type': '', 'package_id': 'd6846542-7785-49ad-8dd4-03a608abb644', 'datastore_active': True, 'id': '1b6be1d3-bd0f-4432-9faa-db12a7de8cb8', 'description': '', 'state': 'active', 'api_access_number': '42', 'size': '174215', 'token_required': 'No', 'hash': '', 'token_name': '', 'format': 'CSV', 'downloads': '154', 'mimetype_inner': None, 'url_type': 'upload', 'token_provider': '', 'column_types': '[Integer, Integer, Integer, String, Integer, String, Integer, String, String]', 'hide_url': 'No', 'token_version': '', 'mimetype': None, 'cache_url': None, 'name': '2021_notaris_compravendes_trans_tip_us_sup.csv', 'created': '2026-03-20T10:46:58.023729', 'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d6846542-7785-49ad-8dd4-03a608abb644/resource/1b6be1d3-bd0f-4432-9faa-db12a7de8cb8/download', 'downloads_absolute': '183', 'map_visualization_res': 'none', 'qa': '{\'updated\': \'2026-10-09T02:09:27.345074\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2026-03-21T02:10:17.029450\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}', 'last_modified': '2026-04-29T12:15:24.996286', 'position': 5, 'revision_id': 'c0d6e357-7e5f-4f5f-a45d-c71eee72858a', 'resource_type': None}, {'api_access_number_absolute': '89', 'cache_last_updated': None, 'incorporated_in_cityos_res': 'No', 'token_type': '', 'package_id': 'd6846542-7785-49ad-8dd4-03a608abb644', 'datastore_active': True, 'id': 'b8178cdb-b450-45bb-aabe-a07125147806', 'description': '', 'state': 'active', 'api_access_number': '45', 'size': '165527', 'token_required': 'No', 'hash': '', 'token_name': '', 'format': 'CSV', 'downloads': '153', 'mimetype_inner': None, 'url_type': 'upload', 'token_provider': '', 'column_types': '[Integer, Integer, Integer, String, Integer, String, Integer, String, String]', 'hide_url': 'No', 'token_version': '', 'mimetype': None, 'cache_url': None, 'name': '2020_notaris_compravendes_trans_tip_us_sup.csv', 'created': '2026-03-20T10:48:20.934594', 'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d6846542-7785-49ad-8dd4-03a608abb644/resource/b8178cdb-b450-45bb-aabe-a07125147806/download', 'downloads_absolute': '183', 'map_visualization_res': 'none', 'qa': '{\'updated\': \'2026-10-09T02:09:27.354273\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2026-03-21T02:10:17.051317\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}', 'last_modified': '2026-04-29T12:14:41.946596', 'position': 6, 'revision_id': 'c0d6e357-7e5f-4f5f-a45d-c71eee72858a', 'resource_type': None}, {'api_access_number_absolute': '91', 'cache_last_updated': None, 'incorporated_in_cityos_res': 'No', 'token_type': '', 'package_id': 'd6846542-7785-49ad-8dd4-03a608abb644', 'datastore_active': True, 'id': '0f9c2bb5-3324-466a-ac8f-43696f6afbfc', 'description': '', 'state': 'active', 'api_access_number': '45', 'size': '192125', 'token_required': 'No', 'hash': '', 'token_name': '', 'format': 'CSV', 'downloads': '153', 'mimetype_inner': None, 'url_type': 'upload', 'token_provider': '', 'column_types': '[Integer, Integer, Integer, String, Integer, String, Integer, String, String]', 'hide_url': 'No', 'token_version': '', 'mimetype': None, 'cache_url': None, 'name': '2019_notaris_compravendes_trans_tip_us_sup.csv', 'created': '2026-03-20T10:49:44.065986', 'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d6846542-7785-49ad-8dd4-03a608abb644/resource/0f9c2bb5-3324-466a-ac8f-43696f6afbfc/download', 'downloads_absolute': '184', 'map_visualization_res': 'none', 'qa': '{\'updated\': \'2026-10-09T02:09:27.365244\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2026-03-21T02:10:17.072109\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}', 'last_modified': '2026-04-29T12:13:25.817053', 'position': 7, 'revision_id': 'c0d6e357-7e5f-4f5f-a45d-c71eee72858a', 'resource_type': None}, {'api_access_number_absolute': '89', 'cache_last_updated': None, 'incorporated_in_cityos_res': 'No', 'token_type': '', 'package_id': 'd6846542-7785-49ad-8dd4-03a608abb644', 'datastore_active': True, 'id': '775168dc-3354-45ee-b2ab-52d249492e00', 'description': '', 'state': 'active', 'api_access_number': '43', 'size': '192193', 'token_required': 'No', 'hash': '', 'token_name': '', 'format': 'CSV', 'downloads': '152', 'mimetype_inner': None, 'url_type': 'upload', 'token_provider': '', 'column_types': '[Integer, Integer, Integer, String, Integer, String, Integer, String, String]', 'hide_url': 'No', 'token_version': '', 'mimetype': None, 'cache_url': None, 'name': '2018_notaris_compravendes_trans_tip_us_sup.csv', 'created': '2026-03-20T10:51:07.672219', 'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d6846542-7785-49ad-8dd4-03a608abb644/resource/775168dc-3354-45ee-b2ab-52d249492e00/download', 'downloads_absolute': '184', 'map_visualization_res': 'none', 'qa': '{\'updated\': \'2026-10-09T02:09:27.374901\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2026-03-21T02:10:17.103183\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}', 'last_modified': '2026-04-29T12:12:56.655964', 'position': 8, 'revision_id': 'c0d6e357-7e5f-4f5f-a45d-c71eee72858a', 'resource_type': None}, {'api_access_number_absolute': '86', 'cache_last_updated': None, 'incorporated_in_cityos_res': 'No', 'token_type': '', 'package_id': 'd6846542-7785-49ad-8dd4-03a608abb644', 'datastore_active': True, 'id': 'e9976d58-16de-44ce-83cf-cd6c78fb4431', 'description': '', 'state': 'active', 'api_access_number': '43', 'size': '198648', 'token_required': 'No', 'hash': '', 'token_name': '', 'format': 'CSV', 'downloads': '152', 'mimetype_inner': None, 'url_type': 'upload', 'token_provider': '', 'column_types': '[Integer, Integer, Integer, String, Integer, String, Integer, String, String]', 'hide_url': 'No', 'token_version': '', 'mimetype': None, 'cache_url': None, 'name': '2017_notaris_compravendes_trans_tip_us_sup.csv', 'created': '2026-03-20T10:52:32.734221', 'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d6846542-7785-49ad-8dd4-03a608abb644/resource/e9976d58-16de-44ce-83cf-cd6c78fb4431/download', 'downloads_absolute': '193', 'map_visualization_res': 'none', 'qa': '{\'updated\': \'2026-10-09T02:09:27.391832\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2026-03-21T02:10:17.132696\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}', 'last_modified': '2026-04-29T12:12:27.948481', 'position': 9, 'revision_id': 'c0d6e357-7e5f-4f5f-a45d-c71eee72858a', 'resource_type': None}, {'api_access_number_absolute': '86', 'cache_last_updated': None, 'incorporated_in_cityos_res': 'No', 'token_type': '', 'package_id': 'd6846542-7785-49ad-8dd4-03a608abb644', 'datastore_active': True, 'id': '914d8655-0584-4aaf-a1ee-6aa4ac5c754e', 'description': '', 'state': 'active', 'api_access_number': '45', 'size': '193419', 'token_required': 'No', 'hash': '', 'token_name': '', 'format': 'CSV', 'downloads': '148', 'mimetype_inner': None, 'url_type': 'upload', 'token_provider': '', 'column_types': '[Integer, Integer, Integer, String, Integer, String, Integer, String, String]', 'hide_url': 'No', 'token_version': '', 'mimetype': None, 'cache_url': None, 'name': '2016_notaris_compravendes_trans_tip_us_sup.csv', 'created': '2026-03-20T10:53:57.088243', 'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/d6846542-7785-49ad-8dd4-03a608abb644/resource/914d8655-0584-4aaf-a1ee-6aa4ac5c754e/download', 'downloads_absolute': '178', 'map_visualization_res': 'none', 'qa': '{\'updated\': \'2026-10-09T02:09:27.403829\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2026-03-21T02:10:17.152378\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}', 'last_modified': '2026-04-29T12:11:55.799647', 'position': 10, 'revision_id': 'c0d6e357-7e5f-4f5f-a45d-c71eee72858a', 'resource_type': None}, {'api_access_number_absolute': '86', 'cache_last_updated': None, 'incorporated_in_cityos_res': 'No', 'token_type': '', 'package_id': 'd6846542-7785-49ad-8dd4-03a608abb644', 'datastore_active': True, 'id': '307e6c2f-8e6e-4b27-8fd9-f01abb394ac2', 'description': '', 'state': 'active', 'api_access_number': '42', 'size': '181007', 'token_required': 'No', 'hash': '', 'token_name': '', 'format': 'CSV', 'downloads': '151', 'mimetype_inner': None, 'url_type': 'upload', 'token_provider': '', 'column_types': '[Integer, Integer, Integer, String, Integer, String, Integer, String, String]', 'hide_url': 'No', 'token_version': '', 'mimetype': None, 'cache_url': None, 'name': '2015_notaris_compravendes_trans_tip_us_sup.csv', 'created': '2026-03-20T10:55:21.140051', 'url': 'https://opendat

In [97]:
url_bcn = "https://opendata-ajuntament.barcelona.cat/data/api/action/package_search"
print ("CATÀLEG DATASETS")
cataleg = requests.get(url_bcn)
print("Hem obtingut",len(cataleg.json()['result']['results']),"dades")
print ("El codi d'estat de la petició és:", cataleg.status_code," -", cataleg.reason)

# L'API retorna un diccionari amb metadades. Els datasets reals estan a ['result']['results']
if cataleg.json() and 'result' in cataleg.json() and 'results' in cataleg.json()['result']:
    datasets = cataleg.json()['result']['results']
    df_cataleg = pd.DataFrame(datasets)
    mostrar_dataframe(df_cataleg, "LLISTA DE DATASETS")
else:
    print("No s'ha pogut obtenir la llista de datasets o el format no és l'esperat.")

CATÀLEG DATASETS
Hem obtingut 10 dades
El codi d'estat de la petició és: 200  - OK

====================================================================================================
LLISTA DE DATASETS
====================================================================================================

,notes_translated,geolocation,dades_alt_valor,url_tornada,dataset_fields_description,fuente,tag,private,num_tags,code,...,url,notes,owner_org,load_type,api,license_url,historical,title,revision_id,extras
0,{'ca': 'Superfície (m²) de les propietats immo...,No,No,"{'ca': '', 'en': '', 'es': ''}",__NOTA:__ Els recursos dels darrers anys poden...,Registres notarials de les compravendes de pro...,"Any 2026,Any 2025,Any 2024,Any 2023,Any 2022,A...",False,17,notaris_compravendes_trans_tip_us_sup,...,None,Surface area (m²) of real estate properties tr...,db34b773-2143-4fe1-a713-fdc11e61e0f1,link_intern_desde_font_interna,Yes,https://creativecommons.org/licenses/by/4.0/,Yes,Area (m²) of real estate properties transmitte...,a2e19e33-c014-422b-8fdd-e7e19559fa72,"[{'key': '01.Any', 'value': 'Any'}, {'key': '0..."
1,{'ca': 'Nombre de transmissions de compravenda...,No,No,"{'ca': '', 'en': '', 'es': ''}",__NOTA:__ Els recursos dels darrers anys poden...,Registres notarials de les compravendes de pro...,"Any 2026,Any 2025,Any 2024,Any 2023,Any 2022,A...",False,17,notaris_compravendes_trans_tip_us,...,None,Number of real estate property sale transactio...,db34b773-2143-4fe1-a713-fdc11e61e0f1,link_intern_desde_font_interna,Yes,https://creativecommons.org/licenses/by/4.0/,Yes,"Number of real estate property transactions, b...",0114aca6-f6db-4e4d-9683-e521e300ec31,"[{'key': '01.Any', 'value': 'Any'}, {'key': '0..."
2,{'ca': 'Quotes sense IVA del padró del preu pú...,No,No,{'ca': 'https://ajuntament.barcelona.cat/netej...,,Ajuntament de Barcelona,"Any 2024,Any 2025,Impost,Quotes,Residus,Preu p...",False,6,rebuts-quota-padro-residus-bcn,...,None,Fees excluding VAT from the public price regis...,5a597816-bbe2-4174-bf69-53644330bb5f,ds_manual,Yes,https://creativecommons.org/licenses/by/4.0/,Yes,Fees excluding VAT from the public price regis...,40ecd8e3-a2c4-4edb-8a43-046710d76cbb,"[{'key': '01.Codi_Districte', 'value': 'Codi d..."
3,{'ca': 'Rebuts i quota del padró de la Taxa de...,No,No,{'ca': 'https://ajuntament.barcelona.cat/hisen...,,Ajuntament de Barcelona,"Rebuts,Quota,Impost,Guals,Any 2025,Any 2024,Pa...",False,7,rebuts-quota-padro-guals,...,None,Receipts and quota of the register of the Vado...,5a597816-bbe2-4174-bf69-53644330bb5f,ds_manual,Yes,https://creativecommons.org/licenses/by/4.0/,Yes,Receipts and quota of the register of the Vado...,bc5f0268-cc97-4091-ac51-ac59ad6fa1fa,"[{'key': '01.Codi_Districte', 'value': 'Codi d..."
4,{'ca': 'Rebuts i quota del padró de l’Impost d...,No,No,{'ca': 'https://ajuntament.barcelona.cat/hisen...,,Ajuntament de Barcelona,"Impost,Quota,Rebuts,Vehicles,IVTM,Any 2025",False,6,rebuts-quota-padro-vehicle-bcn,...,None,Receipts and quota of the vehicle excise tax r...,5a597816-bbe2-4174-bf69-53644330bb5f,ds_manual,Yes,https://creativecommons.org/licenses/by/4.0/,Yes,Receipts and charges from the motor vehicle ta...,86f63e1d-71b6-42b4-bd8b-e25ffb09695d,"[{'key': '01.Codi_Districte', 'value': 'Codi d..."
5,{'ca': 'Nombre de persones immigrants a Barcel...,No,No,"{'ca': '', 'en': '', 'es': ''}",Les dades dels fluxos padronals estan sotmeses...,Ajuntament de Barcelona. Oficina Municipal de ...,"Any 1997,Any 1998,Any 1999,Any 2000,Any 2001,A...",False,31,pad_imm_mdbas,...,None,Number of immigrant people in Barcelona by yea...,bec2fda0-7697-4c99-a635-5fd159334034,link_intern_desde_font_interna,Yes,https://creativecommons.org/licenses/by/4.0/,Yes,Immigrants,75cba241-1e6f-4ff5-94e9-50692d2ac005,"[{'key': '01.Any', 'value': 'Any del moviment'..."
6,{'ca': 'Nombre de persones emigrants a Barcelo...,No,No,"{'ca': '', 'en': '', 'es': ''}",Les dades dels fluxos padronals estan sotmeses...,Ajuntament de Barcelona. Oficina Municipal de ...,"Any 1997,Any 1998,Any 1999,Any 2000,Any 2001,A...",False,31,pad_emi_mdbas,...,None,Number of emigrant people in Barcelona by year...,bec2fda0-7697-4c99-a635-5fd159334034,link_intern_desde_font_interna,Yes,https://creativecommons.org/licenses/by/4.0/,Yes,Emigrants,04f4ef1a-d526-4af6-9d64-d5b5b39bca97,"[{'key': '01.Any', 'value': 'Any del moviment'..."
7,{'ca': 'Nombre de baixes per inscripció indegu...,No,No,"{'ca': '', 'en': '', 'es': ''}",Les dades dels fluxos padronals estan sotmeses...,Ajuntament de Barcelona. Oficina Municipal de ...,"Any 1997,Any 1998,Any 1999,Any 2000,Any 2001,A...",False,32,pad_bai_mdbas,...,None,Number of cancellations due to improper regist...,bec2fda0-7697-4c99-a635-5fd159334034,link_intern_desde_font_interna,Yes,https://creativecommons.org/licenses/by/4.0/,Yes,Cancellations for undue inscription,89d345dc-1359-4497-b170-e07c6cbd1248,"[{'key': '01.Any', 'value': 'Any del moviment'..."
8,{'ca': 'Nombre de defuncions a Barcelona per a...,No,Estadistica,"{'ca': '', 'en': '', 'es': ''}",Les dades dels fluxos padronals estan sotmeses...,Ajuntament de Barcelona. Oficina Municipal de ...,"Any 1997,Any 1998,Any 1999,Any 2000,Any 2001,A...",False,33,pad_def_mdbas,...,None,Number of deaths in Barcelona by year by the t...,bec2fda0-7697-4c99-a635-5fd159334034,link_intern_desde_font_interna,Yes,https://creativecommons.org/licenses/by/4.0/,Yes,Deaths,1dfa1ab5-0e9c-4f2d-90e8-a6e6fc7dbf96,"[{'key': '01.Any', 'value': 'Any del moviment'..."
9,{'ca': 'Nombre d’altes per omissió a Barcelona...,No,No,"{'ca': '', 'en': '', 'es': ''}",Les dades dels fluxos padronals estan sotmeses...,Ajuntament de Barcelona. Oficina Municipal de ...,"Any 1997,Any 1998,Any 1999,Any 2000,Any 2001,A...",False,31,pad_alt_mdbas,...,None,Number of Registrations by omission in Barcelo...,bec2fda0-7697-4c99-a635-5fd159334034,link_intern_desde_font_interna,Yes,https://creativecommons.org/licenses/by/4.0/,Yes,Registrations by omission,5bfa82bd-bf4b-4bd4-8b2d-c549c7f6d11b,"[{'key': '01.Any', 'value': 'Any del moviment'..."