
# **Tasca S10.01. APIs REST**

Aplicaràs el que has après sobre APIs REST, mètodes HTTP i codis d'estat, utilitzant APIs públiques per consultar dades, filtrar-les i finalment desar-les en un DataFrame de pandas..

# **📚 Llibreries**

In [45]:
import requests # llibreria per fer peticions a internet
import json # llibreria per processar i interpretar text en format JSON
import pandas as pd # llibreria per processar dades

# **♻ Re-utilització de funcions:**

In [46]:
def mostrar_dataframe(df, títol):
#Presenta les dades en format tabular amb el títol indicat

    # Mostrem títol
    print("\n" + "="*100)
    print(títol)
    print("="*100)
    # La funció display mostra les dades del dataframe en format taula.
    display(df)

# **Nivell 1: Exploració bàsica amb una API de laboratori.**

Des d’un Jupyter Notebook faràs els següents exercicis utilitzant la llibreria requests de Python.

Exploració bàsica amb una API de laboratori.
1. Consulta l’API pública JSONPlaceholder utilitzant el mètode GET per obtenir:
    *   Llista de publicacions (/posts)
    *   Llista d’usuaris (/users)
    *   Llista de tasques (/todos)

2. Mostra per pantalla:
    *   La quantitat total de cada recurs.
    *   El codi d'estat de cada petició.

3. Fes una petició a una publicació inexistent per obtenir un error 404 i mostra el codi d'estat rebut.

4. Fes una petició POST per crear una nova publicació fictícia. Inclou el títol, el cos del missatge i un userId.
    *   Mostra la resposta JSON.
    *   Mostra el codi d'estat.

5. Fes una petició PATCH per modificar parcialment una publicació existent.
    *   Mostra la resposta JSON.
    *   Mostra el codi d'estat.

6. Fes una petició DELETE sobre una publicació.
    *   Mostra la resposta JSON.
    *   Mostra el codi d'estat.

# **Disseny i implementació de la solució**

### ***A. Mètode GET***

1. Consulta l’API pública JSONPlaceholder utilitzant el mètode GET per obtenir:
    *   Llista de publicacions (/posts)
    *   Llista d’usuaris (/users)
    *   Llista de tasques (/todos)

2. Mostra per pantalla:
    *   La quantitat total de cada recurs.
    *   El codi d'estat de cada petició.

In [47]:
# DEFINICIÓ DE LA FUNCIÓ

def obtenir_dades (url, text):
# Envia una petició GET a la URL indicada per obtenir-ne el contingut.
# El resultat (la resposta del servidor) es desa a la variable resposta
  print (text)
  resposta = requests.get(url)
  print("Hem obtingut",len(resposta.json()),"dades")
  print ("El codi d'estat de la petició és:", resposta.status_code," -", resposta.reason)
  return resposta.json()

# DADES
url_posts = "https://jsonplaceholder.typicode.com/posts"
url_usuaris = "https://jsonplaceholder.typicode.com/users"
url_tasques = "https://jsonplaceholder.typicode.com/todos"


# EXECUCIÓ
llista_publicacions = obtenir_dades (url_posts, "LLISTA DE PUBLICACIONS")
llista_usuaris = obtenir_dades (url_usuaris, "LLISTA D'USUARIS")
llista_tasques = obtenir_dades (url_tasques, "LLISTA DE TASQUES")

LLISTA DE PUBLICACIONS
Hem obtingut 100 dades
El codi d'estat de la petició és: 200  - OK
LLISTA D'USUARIS
Hem obtingut 10 dades
El codi d'estat de la petició és: 200  - OK
LLISTA DE TASQUES
Hem obtingut 200 dades
El codi d'estat de la petició és: 200  - OK

3. Fes una petició a una publicació inexistent per obtenir un error 404 i mostra el codi d'estat rebut.

In [48]:
# DADES
url_novalida = "https://jsonplaceholder.typicode.com/publicacions"

# EXECUCIÓ
obtenir_dades (url_novalida, "PUBLICACIÓ INEXISTENT")

PUBLICACIÓ INEXISTENT
Hem obtingut 0 dades
El codi d'estat de la petició és: 404  - Not Found

{}

### ***B. Mètode POST***

4. Fes una petició POST per crear una nova publicació fictícia. Inclou el títol, el cos del missatge i un userId.
    *   Mostra la resposta JSON.
    *   Mostra el codi d'estat.

In [49]:
# DEFINICIÓ DE LA FUNCIÓ

def enviar_dades (url, dades):
  print ("ENVIAMENT DE DADES")
  resposta = requests.post(url, dades)
  print ("La resposta JSON és:", resposta.json())
  print ("El codi d'estat de la petició és:", resposta.status_code," -", resposta.reason)


# DADES
dades = {"userId": 99, "title": "Prova55", "body": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit"}

# EXECUCIÓ
enviar_dades (url_posts, dades)

ENVIAMENT DE DADES
La resposta JSON és: {'userId': '99', 'title': 'Prova55', 'body': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'id': 101}
El codi d'estat de la petició és: 201  - Created

### ***C. Mètode PATCH***

5. Fes una petició PATCH per modificar parcialment una publicació existent.
    *   Mostra la resposta JSON.
    *   Mostra el codi d'estat.

In [50]:
# DEFINICIÓ DE LA FUNCIÓ

def modificar_dades (url, dades):
  print ("MODIFICACIÓ DE DADES")
  resposta = requests.patch(url, json=dades)
  print ("La resposta JSON és:", resposta.json())
  print ("El codi d'estat de la petició és:", resposta.status_code," -", resposta.reason)


# DADES
# Modifiquem el post 1 afegint el seu ID a la URL
url_patch = "https://jsonplaceholder.typicode.com/posts/1"
dades = {"title": "Prova66", "body": "Hola"}

# EXECUCIÓ
modificar_dades (url_patch, dades)

MODIFICACIÓ DE DADES
La resposta JSON és: {'userId': 1, 'id': 1, 'title': 'Prova66', 'body': 'Hola'}
El codi d'estat de la petició és: 200  - OK

### ***D. Mètode DELETE***

6. Fes una petició DELETE sobre una publicació.
    *   Mostra la resposta JSON.
    *   Mostra el codi d'estat.

In [51]:
# DEFINICIÓ DE LA FUNCIÓ

def esborrar_dades (url):
  print ("ELIMINACIÓ DE DADES")
  resposta = requests.delete(url)
  print ("La resposta JSON és:", resposta.json())
  print ("El codi d'estat de la petició és:", resposta.status_code," -", resposta.reason)


# DADES
# Esborrem  el post 1 afegint el seu ID a la URL
url_del = "https://jsonplaceholder.typicode.com/posts/1"

# EXECUCIÓ
esborrar_dades (url_del)

ELIMINACIÓ DE DADES
La resposta JSON és: {}
El codi d'estat de la petició és: 200  - OK

# **Nivell 2: Interacció amb una API pública real**

1. Explora el repositori de Public APIs i tria una API que permeti fer peticions GET.

2. Llegeix la documentació de l'API:

    *   Revisa la secció d’endpoints disponibles. En un markdown, apunta com a mínim dos endpoints diferents.
    *   Comprova si ofereix filtres o paràmetres opcionals interessants. En un markdown, anota’ls.
    *   Verifica que la resposta sigui en format JSON (és el més adequat per a aquest exercici).

3. Fes una petició GET senzilla:
    *   Mostra el codi d'estat de la resposta.
    *   Imprimeix de forma clara alguns dels camps de la resposta JSON.

4. Converteix les dades a un DataFrame de pandas:
    *   Mostra les primeres files del DataFrame.

# **Disseny i implementació de la solució**

Treballarem amb la següent API:
**Exchangerate.host API**

Ens permet obtenir els canvis de moneda actuals i històrics.

La URL base és: https://api.exchangerate.host/

Endpoints:

*   /live: per obtenir el canvi més recent
*   /historical: retorna canvi a una data determinada
*   /convert: converteix un import d'una moneda a una altra
*   /timeframe: per obtenir canvi entre dues dates
*   /change: per obtenir les fluctuacions del canvi
*   /list: per obtenir llista de monedes

Tots els endpoints retornen dades estructurades en format JSON.

Finalment utilitzem **Frankfurter API**, que és 100% gratuïta i no necessita access_key.

**url:** https://api.frankfurter.app/mètode

**mètodes:**
*   /latest: per obtenir l'últim canvi
*   /rates: llista de canvis de dòlar a altres divises
*   /currencies: llista de divises

### ***1. Obtenir canvi de USD a EUR***

In [52]:
# Utilitzem Frankfurter API amb el mètode latest
url_canvi = "https://api.frankfurter.app/latest?from=USD&to=EUR"
resposta_json = obtenir_dades(url_canvi, "CANVI ACTUAL DE USD A EUR")

print("")
print("Moneda base:", resposta_json['base'])
print("Data:", resposta_json['date'])
print("Canvi a moneda destí:", resposta_json['rates'])

CANVI ACTUAL DE USD A EUR
Hem obtingut 4 dades
El codi d'estat de la petició és: 200  - OK

Moneda base: USD
Data: 2026-10-09
Canvi a moneda destí: {'EUR': 0.89238}

### ***2. Obtenir llista de canvis***

In [53]:
# Utilitzem Frankfurter API amb el mètode rates
url_canvi = "https://api.frankfurter.dev/v2/rates"
json_canvis = obtenir_dades(url_canvi, "LECTURA DE CANVIS")

# Creem el DataFrame correctament a partir del json de la resposta
df_canvis = pd.DataFrame(json_canvis)
mostrar_dataframe(df_canvis.head(), "LLISTA DE CANVIS")

LECTURA DE CANVIS
Hem obtingut 165 dades
El codi d'estat de la petició és: 200  - OK

====================================================================================================
LLISTA DE CANVIS
====================================================================================================

         date base quote      rate
0  2026-10-11  EUR   AED    4.1193
1  2026-10-11  EUR   AFN   72.7390
2  2026-10-11  EUR   ALL   91.6900
3  2026-10-11  EUR   AMD  405.4600
4  2026-10-09  EUR   ANG    2.0078

### ***2. Obtenir llista de divises***

In [54]:
# Utilitzem Frankfurter API amb el mètode currencies
url_divises = "https://api.frankfurter.dev/v2/currencies"
json_divises = obtenir_dades(url_divises, "LECTURA DE DIVISES")

# Creem el DataFrame correctament a partir del json de la rerposta
df_divises = pd.DataFrame(json_divises)
mostrar_dataframe(df_divises.head(),"LLISTA DE DIVISES")

LECTURA DE DIVISES
Hem obtingut 165 dades
El codi d'estat de la petició és: 200  - OK

====================================================================================================
LLISTA DE DIVISES
====================================================================================================

,iso_code,iso_numeric,name,symbol,start_date,end_date
0,AED,784,United Arab Emirates Dirham,د.إ,1996-04-11,2026-10-11
1,AFN,971,Afghan Afghani,؋,2003-01-07,2026-10-11
2,ALL,008,Albanian Lek,L,1998-07-07,2026-10-11
3,AMD,051,Armenian Dram,֏,1994-03-18,2026-10-11
4,ANG,532,Netherlands Antillean Guilder,ƒ,1971-12-18,2026-10-11

# **Nivell 3: API d'Open Data Barcelona**

1. Utilitza l’API d’Open Data BCN per:
      *   Cercar un dataset del teu interès mitjançant package_search i package_show.

2. Dels resultats obtinguts, selecciona’n un que tingui recursos disponibles en CSV o JSON.


3. Amb el resource_id del recurs seleccionat, realitza una consulta mitjançant datastore_search per:
      *   Recuperar almenys 100 registres.

4. Converteix els resultats a un DataFrame.


5. Desa el DataFrame en un fitxer .csv.

# **Disseny i implementació de la solució**

**API de gestió del catàleg**

*   url base: https://opendata-ajuntament.barcelona.cat/data/api/
*   url per accedir-hi: https://opendata-ajuntament.barcelona.cat/data/api/action/mètode

Aquests **mètodes** són públics i no requereixen cap tipus d'identificació ni token sent alguns exemples:


*   **current_package_list_with_resources**: retorna el llistat de datasets actuals i els seus recursos
*   **package_search**: fa una cerca dins del catàleg de datasets
*   **resource_show**: retorna les metadades del dataset a partir de l'id del dataset i entre elles el resource_id dels recursos
*   **datastore_search**: retorna la informació de cada recurs.

In [55]:
# Base URL de l'API de CKAN d'Open Data BCN
BASE_URL = "https://opendata-ajuntament.barcelona.cat/data/api/action"

### ***1. Cerca de datasets mitjançant package_search***

In [56]:
# -----------------------------------------------------------------------------
# 1. Cerca de datasets mitjançant package_search
# -----------------------------------------------------------------------------
query = "aparcaments"
search_url = f"{BASE_URL}/package_search?q={query}"
cataleg = requests.get(search_url)
# L'API retorna un diccionari amb metadades. Els datasets reals estan a ['result']['results']
print("Hem obtingut",len(cataleg.json()['result']['results']),"dades")
print ("El codi d'estat de la petició és:", cataleg.status_code," -", cataleg.reason)

# Agafem el primer resultat trobat
results = cataleg.json()["result"]["results"]

# Convertim a dataframe i mostrem
df_cataleg = pd.DataFrame(results)
mostrar_dataframe(df_cataleg, "LLISTA DE DATASETS")

Hem obtingut 10 dades
El codi d'estat de la petició és: 200  - OK

====================================================================================================
LLISTA DE DATASETS
====================================================================================================

,notes_translated,geolocation,code,url_tornada,dataset_fields_description,fuente,private,num_tags,api,frequency,...,notes,owner_org,load_type,tag,license_url,historical,title,revision_id,extras,dades_alt_valor
0,{'ca': 'Inventari d'aparcaments de rotació de...,Yes_no_map_view,aparcaments-sota-superficie,"{'ca': 'http://www.aparcamentsbsm.cat/', 'en':...",__IMPORTANT: Per tal d'oferir un millor servei...,Barcelona de Serveis Municipals,False,2,No,IMMEDIATA,...,Off-street B:SM (Barcelona de Serveis Municipa...,50bee103-b517-4728-838e-fc0d6b19e91f,link_extern,"BSM,Aparcaments",https://creativecommons.org/licenses/by/4.0/,No,Off-street parking inventory of the B:SM netwo...,ef9e2bcf-7875-4660-9cba-9e311428f9d7,"[{'key': '00.ParkingList', 'value': 'Llistat d...",NaN
1,{'ca': 'Informació dels horaris dels aparcamen...,No,horaris aparcaments superficie,"{'ca': 'https://www.areaverda.cat/', 'en': 'ht...",Les dades d’aquest dataset complementen les d'...,Divisió MOBILITAT BSM,False,14,Yes,MENSUAL,...,Timetables' information about regulated surfac...,50bee103-b517-4728-838e-fc0d6b19e91f,link_intern_desde_font_externa,"Aparcaments,Àrea DUM,Àrea blava,Àrea verda,Any...",https://creativecommons.org/licenses/by/4.0/,Yes,Surface parking spots timetables' information ...,651e9578-b5da-4518-900b-1527f286c9f5,"[{'key': '01.ID_HORARI', 'value': 'Número iden...",NaN
2,{'ca': 'Informació dels trams dels aparcaments...,Yes_with_map_view,trams aparcament superficie,"{'ca': 'https://www.areaverda.cat/', 'en': 'ht...",,Divisió MOBILITAT BSM,False,14,Yes,MENSUAL,...,Zones' information about regulated surface pai...,50bee103-b517-4728-838e-fc0d6b19e91f,link_intern_desde_font_externa,"Aparcaments,Àrea DUM,Àrea blava,Àrea verda,Any...",https://creativecommons.org/licenses/by/4.0/,Yes,Surface parking spots zones' information in th...,46c1f989-4be2-4fe6-81aa-a6565da7e808,"[{'key': '01.ID_TRAMO', 'value': 'Codi identif...",NaN
3,{'ca': 'Informació de les tarifes dels aparcam...,No,tarifes aparcament superficie,"{'ca': 'https://www.areaverda.cat/', 'en': 'ht...",Les dades d’aquest dataset complementen les d'...,Divisió MOBILITAT BSM,False,14,Yes,MENSUAL,...,Rates information about regulated surface park...,50bee103-b517-4728-838e-fc0d6b19e91f,link_intern_desde_font_externa,"Aparcaments,Àrea DUM,Àrea blava,Àrea verda,Any...",https://creativecommons.org/licenses/by/4.0/,Yes,Surface parking spots rates' information in th...,9254b3a6-a0bf-4b02-89eb-68eecff153e1,"[{'key': '01.ID_TARIFA', 'value': 'Número iden...",NaN
4,{'ca': 'Informació dels colors dels aparcament...,No,colors aparcaments superficie,"{'ca': 'https://www.areaverda.cat/', 'en': 'ht...",Les dades d’aquest dataset complementen les d'...,Divisió MOBILITAT BSM,False,6,Yes,MENSUAL,...,Colors' information about regulated surface pa...,50bee103-b517-4728-838e-fc0d6b19e91f,link_intern_desde_font_externa,"Aparcaments,Àrea DUM,Àrea blava,Àrea verda,Any...",https://creativecommons.org/licenses/by/4.0/,Yes,Surface parking spots colours' information in ...,13303370-2e6f-4e57-bf74-a4a579b25813,"[{'key': '01.COLORS', 'value': 'Nom dels color...",No
5,{'ca': 'Aparcaments a la ciutat de Barcelona '...,Yes_with_map_view,APARCAMENTS_BCN,"{'ca': 'https://w33.bcn.cat/planolBCN/ca/', 'e...",,Ajuntament de Barcelona,False,2,Yes,SETMANAL,...,Car parks in the city of Barcelona,50bee103-b517-4728-838e-fc0d6b19e91f,link_extern,"Aparcaments,Plànol BCN",https://creativecommons.org/licenses/by/4.0/,No,Car parks in the city of Barcelona,fafecf6b-e862-4890-a72c-8e1bfdc09769,"[{'key': '*00.', 'value': '__ESTRUCTURA RECURS...",NaN
6,{'ca': 'Equipaments de la tipologia Transports...,Yes_with_map_view,EQUIPAMENT_TRANSPORTS_I_SERVEIS_RELACIONATS,"{'ca': 'https://com-shi-va.barcelona.cat/ca', ...",,Ajuntament de Barcelona,False,3,Yes,SETMANAL,...,Types of Transport and related services to be ...,50bee103-b517-4728-838e-fc0d6b19e91f,link_extern,"Equipaments,Transport,Transports i Serveis rel...",https://creativecommons.org/licenses/by/4.0/,No,List of transportation equipments and related ...,68139be6-22e8-41b1-ac7b-6a121646bc0a,"[{'key': '*00.', 'value': '__ESTRUCTURA RECURS...",NaN
7,{'ca': 'Empreses de lloguer i altres serveis ...,Yes_with_map_view,BICICLETES,{'ca': 'https://guia.barcelona.cat/ca/llistat?...,,Ajuntament de Barcelona,False,4,Yes,SETMANAL,...,Rental companies and other services related w...,50bee103-b517-4728-838e-fc0d6b19e91f,link_extern,"Bicicletes,Transport,Lloguer,Bicicletes i Serv...",https://creativecommons.org/licenses/by/4.0/,No,Services related with bicycles in the city of ...,cafc7521-6098-4c35-9f37-41d3eae07728,"[{'key': '*00.', 'value': '__ESTRUCTURA RECURS...",NaN
8,{'ca': 'Aparcaments amb servei per bicis a la ...,Yes_with_map_view,APARCAMENTS_SERVEI_BICIS,"{'ca': 'https://w33.bcn.cat/planolBCN/ca/', 'e...",,Ajuntament de Barcelona,False,5,Yes,SETMANAL,...,Parking service for bikes in the city of Barce...,50bee103-b517-4728-838e-fc0d6b19e91f,link_extern,"Bicicletes,Aparcaments,Transports,Plànol BCN,S...",https://creativecommons.org/licenses/by/4.0/,No,Parking service for bikes in the city of Barce...,96c212a1-d661-45be-8055-b311d020923a,"[{'key': '*00.', 'value': ' __ESTRUCTURA RECUR...",NaN
9,{'ca': 'Punts d'ancoratge de bicicletes de la ...,Yes_no_map_view,PUNTS_ANCORATGE_BICICLETES,{'ca': 'http://ajuntament.barcelona.cat/bicicl...,__IMPORTANT:__ Amb data 14/7/2022 i degut a un...,Ajuntament de Barcelona,False,10,No,SETMANAL,...,Bicycles's anchorage points in the city of Bar...,50bee103-b517-4728-838e-fc0d6b19e91f,link_extern,"Aparcaments,Bicicletes,Punts ancoratge,Transpo...",https://creativecommons.org/licenses/by/4.0/,Yes,Bicycles's anchorage points in the city of Bar...,a9c6516a-503e-4021-8ec8-dc4df68720dc,"[{'key': '00.', 'value': '__ESTRUCTURA RECURS ...",NaN

### ***2. Obtenir informació detallada del dataset mitjançant package_show***

In [57]:
# -----------------------------------------------------------------------------
# 2. Obtenir informació detallada del dataset mitjançant package_show
# -----------------------------------------------------------------------------

# Cerquem quins recursos de tots els datasets obtinguts tenen el Datastore actiu i format CSV o JSON
recursos_actius = []

for dataset in results:
    # Obtenim la informació detallada de cada dataset per veure els seus recursos
    show_url = f"{BASE_URL}/package_show?id={dataset['id']}"
    info = requests.get(show_url).json()

    if info.get("success"):
        for res in info["result"]["resources"]:
            fmt = res.get("format", "").upper()
            # Verifiquem si el format és CSV o JSON i té id de recurs
            if fmt in ["CSV", "JSON"] and resource.get("id"):
              if res.get("datastore_active"):
                  recursos_actius.append({
                    "Dataset": dataset["title"],
                    "Recurs": res["name"],
                    "Format": res["format"],
                    "Resource_ID": res["id"]
                  })

# Convertim a DataFrame i els mostrem
if recursos_actius:
    df_actius = pd.DataFrame(recursos_actius)
    mostrar_dataframe(df_actius, "RECURSOS AMB DATASTORE ACTIU  I FORMAT CSV O JSON")
else:
    print("No s'ha trobat cap recurs amb Datastore actiu en la cerca actual. Prova de canviar la query de cerca a una més general com 'api' o 'estacio'.")

====================================================================================================
RECURSOS AMB DATASTORE ACTIU  I FORMAT CSV O JSON
====================================================================================================

,Dataset,Recurs,Format,Resource_ID
0,Surface parking spots timetables' information ...,HORARIS.csv,CSV,3e8b6626-e221-428c-8bec-3238fee1fe1e
1,Surface parking spots zones' information in th...,TRAMS.csv,CSV,26f6ecdd-b0ac-46c4-84f0-a312640913ca
2,Surface parking spots rates' information in th...,TARIFES.csv,CSV,30c5d684-fd4a-4229-9ec4-101fde46e512
3,Surface parking spots colours' information in ...,COLORES.csv,CSV,409a7f2d-f62a-407b-a3d7-436026fd858d
4,Surface parking spots colours' information in ...,2018_05_COLORES.CSV,CSV,63b6cea4-b109-480a-9fed-d9e47f40c383
5,Car parks in the city of Barcelona,opendatabcn_transports_aparcaments_aparcaments...,CSV,8104b9b9-217e-4c7d-b323-c7b4419d2800
6,List of transportation equipments and related ...,opendatabcn_llista-equipaments_transports-serv...,CSV,dd70f3f8-7abf-4f0a-934c-e2570e53e9cb
7,Services related with bicycles in the city of ...,opendatabcn_bicicletes-csv.csv,CSV,d8cbcb13-a6ac-4d83-a67d-6d672c39d7f5
8,Parking service for bikes in the city of Barce...,opendatabcn_transports_bicis_aparcaments-serve...,CSV,797cf565-d91f-4039-8cfe-5b3263c84837

### ***3. Consultar registres mitjançant datastore_search i convertir a dataframe***

In [58]:
# -----------------------------------------------------------------------------
# 3. Consultar registres mitjançant datastore_search
# -----------------------------------------------------------------------------

selected_resource_id = "797cf565-d91f-4039-8cfe-5b3263c84837"

datastore_url = f"{BASE_URL}/datastore_search"
params = {"resource_id": selected_resource_id, "limit": 100}

datastore_response = requests.get(datastore_url, params=params).json()

records = datastore_response["result"]["records"]
print(f"S'han recuperat {len(records)} registres.")

df = pd.DataFrame(records)
mostrar_dataframe(df, "RESULTATS DE LA CONSULTA")

S'han recuperat 100 registres.

====================================================================================================
RESULTATS DE LA CONSULTA
====================================================================================================

,addresses_roadtype_name,addresses_end_street_number,geo_epgs_4326_lon,values_attribute_name,estimated_dates,addresses_road_name,values_category,addresses_zip_code,secondary_filters_id,values_value,...,institution_name,modified,secondary_filters_asia_id,secondary_filters_fullpath,geo_epgs_4326_lat,values_description,values_id,addresses_neighborhood_name,values_outstanding,values_attribute_id
0,,None,2.1334060660078245,Tel.,,C Josep Balari,Telèfons,8022,63734068,934179356,...,,2015-02-23T13:57:46,65103010003000,Planol BCN >> Transports i serveis relacionats...,41.40152762909788,,171311,Sant Gervasi - la Bonanova,True,20001
1,,None,2.1334060660078245,Tel.,,C Josep Balari,Telèfons,8022,63736072,934179356,...,,2015-02-23T13:57:46,65103010005004,Planol BCN >> Transports i serveis relacionats...,41.40152762909788,,171311,Sant Gervasi - la Bonanova,True,20001
2,,None,2.177303061122395,Tel.,,C Mallorca,Telèfons,8013,63734068,934365155,...,,2015-02-23T14:05:20,65103010003000,Planol BCN >> Transports i serveis relacionats...,41.40505509128825,,184527,la Sagrada Família,True,20001
3,,None,2.177303061122395,Tel.,,C Mallorca,Telèfons,8013,63736072,934365155,...,,2015-02-23T14:05:20,65103010005004,Planol BCN >> Transports i serveis relacionats...,41.40505509128825,,184527,la Sagrada Família,True,20001
4,,None,2.1806022091290447,Tel.,,Pg Maragall,Telèfons,8041,63734068,934351039,...,,2015-02-23T14:02:52,65103010003000,Planol BCN >> Transports i serveis relacionats...,41.41614143901906,,184526,el Camp de l'Arpa del Clot,True,20001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,,None,2.1910365479757883,Atenció al client,,C Badajoz,Telèfons,8018,63734068,933284949,...,,2015-02-23T13:03:55,65103010003000,Planol BCN >> Transports i serveis relacionats...,41.40214569463325,,226062,el Parc i la Llacuna del Poblenou,True,20005
96,,None,2.1910365479757883,Atenció al client,,C Badajoz,Telèfons,8018,63736072,933284949,...,,2015-02-23T13:03:55,65103010005004,Planol BCN >> Transports i serveis relacionats...,41.40214569463325,,226062,el Parc i la Llacuna del Poblenou,True,20005
97,,None,2.1425376125220716,Atenció al client,,Av Josep Tarradellas,Telèfons,8029,63734068,662418060,...,,2024-10-11T12:56:55.176766,65103010003000,Planol BCN >> Transports i serveis relacionats...,41.38287903281645,Whatsapp,205717,la Nova Esquerra de l'Eixample,True,20005
98,,None,2.1425376125220716,Atenció al client,,Av Josep Tarradellas,Telèfons,8029,63736072,662418060,...,,2024-10-11T12:56:55.176766,65103010005004,Planol BCN >> Transports i serveis relacionats...,41.38287903281645,Whatsapp,205717,la Nova Esquerra de l'Eixample,True,20005
99,,None,2.1334975833851173,Tel.,,Pl Bonanova,Telèfons,8022,63734068,934189385,...,,2015-02-23T14:08:38,65103010003000,Planol BCN >> Transports i serveis relacionats...,41.406819626163255,,215970,Sant Gervasi - la Bonanova,True,20001

### ***4. Desar en un fitxer .csv***

In [59]:
# -----------------------------------------------------------------------------
# 4. Desar en un fitxer .csv
# -----------------------------------------------------------------------------

# Guardem el DataFrame a un fitxer CSV local
output_file = "resultats_opendata_bcn.csv"
df.to_csv(output_file, index=False, encoding="utf-8")

print(f"El fitxer s'ha desat correctament com a '{output_file}'.")

El fitxer s'ha desat correctament com a 'resultats_opendata_bcn.csv'.