# **Nivell 1**

# **Exercici 1: Selecció de Personal**

Tu treballes com a **analista de dades** en el **departament de RRHH** d'una empresa. S'ha obert una nova oferta laboral interna i l'empresa ha decidit que només les primeres 10 persones que s'inscriguin podran participar en el procés de selecció.

Per això, t'han encarregat desenvolupar una eina senzilla en Python que actuï com a **formulari d'inscripció** i sistema de classificació inicial. Aquest formulari ha de permetre introduir, per a cada candidat/a:


*   Nom i Cognoms
*   Telèfon de contacte
*   Anys d'experiència dins de l'empresa
*   Coneixement de Català (0–3 punts)
    *   0 = sense coneixement
    *   1 = fins a nivell B1
    *   2 = nivell B2
    *   3 = C1 o superior
*   Domini d'Excel (0-3 punts)
    *   0 = nivell bàsic
    *   1 = ús de funcions
    *   2 = taules dinàmiques
    *   3 = Visual Basic i Macros
*   Títol acadèmic (0-3 punts)
    *   0 = ESO
    *   1 = FP
    *   2 = Universitat
    *   3 = Màster o superior

Assegurant-se que tota la informació introduïda és correcta i entra dins els valors permesos. A partir d'aquestes dades, el programa haurà de calcular una puntuació total aplicant el pes de l'experiència (anys * 1.5) i sumant-hi els punts de català, excel i titulació, i a continuació classificar automàticament cada persona segons els llindars establerts per l'empresa:

*   Prioritat Alta → puntuació ≥ 12
*   Candidat adequat → 8 ≤ puntuació < 12
*   No prioritari → puntuació < 8

Cada vegada que algú completa el formulari, s'ha de mostrar la seva puntuació individual. Quan ja s'hagin inscrit exactament deu persones, l'eina ha de deixar d'acceptar nous registres i generar un informe final en pantalla, ordenat primer segons la prioritat i, en cas d'empat, per la puntuació obtinguda. Aquest informe ha d'incloure el nom, el telèfon i la puntuació de cada candidat per tal que el departament de RRHH els pugui contactar ràpidament.

Per resoldre aquest exercici, hauràs de:

» Desenvolupar un sistema modular amb les funcions següents:
*   obtenir_dades
*   validar_dades
*   calcular_puntuacio
*   classificar_candidat
*   mostrar_individual
*   mostrar_informe
*   main_seleccio # orquestra totes les funcions

» Escriure primer l'algoritme pas a pas, indicant clarament quines operacions farà cada funció.
» Escriure el codi de cada funció.

# **Disseny i implementació de la solució**

## 🧠 **Algoritme inicial**

1. Per cada usuari:
    *   Demanar dades a l'usuari via input.
    *   Validar que les dades estiguin dins els rangs.
    *   Calcular la puntuació.
    *   Classificar el candidat.
    *   Mostrar la puntuació individual.
2. Mostrar informe final.

# **📚 Llibreries**

Importem la **llibreria pandas** per poder crear un dataframe i utilitzar els mètodes associats.

In [68]:
import pandas as pd

## **💢 Estructures de dades**

In [69]:
inputs_test = [
    "Laura Serra", "608112233", 6, 3, 3, 3,
    "Clara Gómez", "655221199", 3, 3, 3, 2,
    "Sergio López", "644112211", 3, 2, 2, 2,
    "Candidat Error", "611000000", 5, 7, 3, 2, # Català = 7 → NO VÀLID
    "Marta Ruiz", "699887766", 2, 3, 2, 1,
    "Marc Vidal", "612443322", 6, 3, 3, 3,
    "Júlia Romero", "677998877", 5, 3, 3, 2,
    "Pol Navarro", "699554433", 4, 3, 2, 2,
    "David Ferrer", "677665544", 2, 1, 1, 1,
    "Anna Paredes", "633221144", 1, 2, 1, 0,
    "Anibal Paredes", "644272727", 1, 2, 1, 0,
    "Núria Casals", "600112200", 8, 2, 3, 3 # 11è candidat
]

Per emmagatzemar la informació de tots els candidats, utilitzarem una **llista de diccionaris**. Cada diccionari representarà un candidat individual i contindrà totes les seves dades, inclosa la puntuació calculada i la seva classificació .

Aquesta estructura és ideal perquè:
- Permet afegir fàcilment nous candidats a la llista.
- Facilita l'accés a les dades de cada candidat per a la classificació i l'ordenació posterior.

## 🧩 **Descomponent el problema: naixement de les funcions**

### ***✔ obtenir_dades()***

Per emmagatzemar la informació de cada candidat utilitzarem un diccionari que contindrà totes les seves dades.

**Tasques:**
1. Demanar les dades al candidat via input i guardar-les al diccionari amb la clau corresponent (nom, telèfon, antiguitat, català, excel i títol)
2. Retornar diccionari amb totes les dades d'un candidat.

In [57]:
def obtenir_dades1():
    #inicialitzem el diccionari
    dades = {}
    #capturem les dades en format string i les guardem al diccionari
    dades['nom'] = input("Introdueix el teu nom i cognoms: ")
    dades['telèfon'] = input("Introdueix el telèfon: ")
    dades['antiguitat'] = input("Introdueix els anys d'experiència a l'empresa: ")
    dades['català'] = input("Introdueix el nivell de coneixement de català: ")
    dades['excel'] = input("Introdueix el nivell de coneixement d'excel: ")
    dades['títol'] = input("Introdueix el tipus de títol acadèmic: ")
    #retornem el diccionari amb les dades del candidat
    return dades

In [71]:
def obtenir_dades(llista_inicial, n):
    #inicialitzem el diccionari amb les dades de la llista_inicial
    dades = {}
    #capturem les dades en format string i les guardem al diccionari
    dades['nom'] = llista_inicial[0+6*n]
    dades['telèfon'] = llista_inicial[1+6*n]
    dades['antiguitat'] = llista_inicial[2+6*n]
    dades['català'] = llista_inicial[3+6*n]
    dades['excel'] = llista_inicial[4+6*n]
    dades['títol'] = llista_inicial[5+6*n]
    #retornem el diccionari amb les dades del candidat
    print(dades)
    return dades

### ***✔ validar_dades(dades)***

**Paràmetre:** diccionari amb les dades d'un candidat.

**Tasques:**
1. Processar les dades entrades:
    - **Convertir** els camps numèrics a enters (antiguitat, català, excel i títol).
    - **Validar** que els camps numèrics anteriors estiguin dins del rang permès.

2. Si falla algun procés mostra missatge d'error i retorna **False**.

3. Si no hi ha errors retorna **True**.

In [72]:
def validar_dades(dades):
    try:
        # Convertim els camps numèrics a tipus enter.
        dades['antiguitat'] = int(dades['antiguitat'])
        dades['català'] = int(dades['català'])
        dades['excel'] = int(dades['excel'])
        dades['títol'] = int(dades['títol'])

        # Validem els rangs de les dades numèriques. Si no estan dins del rang permès mostrem missatge i retornem False.
        if not (0 <= dades['català'] <= 3):
            print("Error: El coneixement de català ha de ser entre 0 i 3.")
            return False
        if not (0 <= dades['excel'] <= 3):
            print("Error: El domini d'Excel ha de ser entre 0 i 3.")
            return False
        if not (0 <= dades['títol'] <= 3):
            print("Error: El títol acadèmic ha de ser entre 0 i 3.")
            return False
        if dades['antiguitat'] < 0:
            print("Error: Els anys d'experiència no poden ser negatius.")
            return False

    #si la conversió dona error mostrem missatge i retornem False
    except ValueError:
        print("Error: Els camps numèrics (antiguitat, català, excel, títol) han de ser nombres enters.")
        return False

    #si no hi ha cap error retornem True
    return True

### ***✔ Calcular_puntuació(dades)***

**Paràmetre:** diccionari amb les dades d'un candidat.

**Tasques:**
1. Calcular la puntuació: català + excel + títol + anys * 1,5
2. Retornar el resultat

In [73]:
def calcular_puntuació(dades):
    #calculem la puntuació
    puntuació = dades['català'] + dades['excel'] + dades['títol'] + dades['antiguitat'] * 1.5
    #retornem el resultat
    return puntuació

### ***✔ classificar_candidat(puntuació)***

**Paràmetre:** valor de la puntuació del candidat.

**Tasques:**
1. Classificar el candidat segons barem:
    *   si puntuació >= 12 --> prioritat alta
    *   si puntuació < 8 --> no prioritari
    *   en els altres casos (8<= puntuació <12) --> candidat adequat
2. Retornar resultat

In [74]:
def classificar_candidat(puntuació):
    #classifiquem el candidat en funció del valor de la puntuació
    if puntuació >= 12:
        classificació = "Prioritat alta"
    elif puntuació < 8:
        classificació = "No prioritari"
    else:
        classificació = "Candidat adequat"

    #retornem el resultat de la classificació
    return classificació

### ***✔ mostrar_individual(puntuació)***

**Paràmetre:** valor de la puntuació del candidat.

**Tasques:**
1. Imprimir en pantalla "La teva puntuació és: x"

In [75]:
def mostrar_individual(puntuació):
    print(f"La teva puntuació és {puntuació}")

### ***✔ ordenar_dataframe(df, camp, ordre)***

**Paràmetres:** dataframe, camp, ordre

**Passos:**
1. Ordena el dataframe pel camp indicat

In [76]:
def ordenar_dataframe(df, camp, ordre):
    #Modifica el dataframe ordenant-lo pel camp indicat i seguint l'ordre indicat (True: ascendent, False: descendent)
    df.sort_values(by=camp, ascending=ordre, inplace=True)

### ***✔ mostrar_dataframe(dataframe, títol)***

**Paràmetre:** dataframe i títol que volem mostrar.

**Passos:**
1. Mostrar títol.
2. Mostrar les dades del dataframe.

In [77]:
def mostrar_dataframe(df, títol):
    #Presenta les dades en format tabular amb el títol indicat
    print("\n" + "="*100)
    print(títol)
    print("="*100)
    #la funció display mostra les dades del dataframe en format taula.
    #utilitzem la propietat style per amagar la columna de l'índex.
    display(df.style.hide(axis='index'))

## 🧠 **Algoritme principal**



### ***✔ main_seleccio():***

1. Mentre num usuaris <= 10:
    *   Demanar dades a l'usuari via input: `obtenir_dades()`
    *   Validar que les dades estiguin dins els rangs: `validar_dades()`
    *   Si la validació és correcta:
        *   Calcular puntuació: `calcular_puntuacio()`
        *   Classificar el candidat: `classificar_candidat()`
        *   Mostrar la puntuació individual: `mostrar_individual()`
2. Mostrar informe final: `mostrar_informe()`

In [78]:
def main_seleccio():
    #inicialitzem la llista de diccionaris on guardarem les dades de tots els candidats.
    print("\n" + "="*100)
    print("ENTRADA DE DADES")
    print("="*100)
    candidats_registrats = []
    i = 0
    while i < 10:
        #inicialitzem el diccionari on guardarem les dades del candidat que està entrant la informació.
        dades_candidat = {}
        #capturem les dades del candidat i les guardem al diccionari
        dades_candidat = obtenir_dades(inputs_test, i)
        #si la validació de les dades retorna True calculem puntuació, classifiquem candidat, mostrem puntuació i afegim a la llista de candidats.
        if validar_dades(dades_candidat):
          dades_candidat['puntuació'] = calcular_puntuació(dades_candidat)
          dades_candidat['classificació'] = classificar_candidat(dades_candidat['puntuació'])
          mostrar_individual(dades_candidat['puntuació'])
          candidats_registrats.append(dades_candidat)
        i += 1
    #mostrem informe ordenat dels candidats.
    df_candidats = pd.DataFrame(candidats_registrats)
    ordenar_dataframe(df_candidats, 'puntuació', False)
    mostrar_dataframe(df_candidats[['nom', 'telèfon','puntuació']], "INFORME FINAL DE CANDIDATS")

In [79]:
main_seleccio()

====================================================================================================
ENTRADA DE DADES
====================================================================================================
{'nom': 'Laura Serra', 'telèfon': '608112233', 'antiguitat': 6, 'català': 3, 'excel': 3, 'títol': 3}
La teva puntuació és 18.0
{'nom': 'Clara Gómez', 'telèfon': '655221199', 'antiguitat': 3, 'català': 3, 'excel': 3, 'títol': 2}
La teva puntuació és 12.5
{'nom': 'Sergio López', 'telèfon': '644112211', 'antiguitat': 3, 'català': 2, 'excel': 2, 'títol': 2}
La teva puntuació és 10.5
{'nom': 'Candidat Error', 'telèfon': '611000000', 'antiguitat': 5, 'català': 7, 'excel': 3, 'títol': 2}
Error: El coneixement de català ha de ser entre 0 i 3.
{'nom': 'Marta Ruiz', 'telèfon': '699887766', 'antiguitat': 2, 'català': 3, 'excel': 2, 'títol': 1}
La teva puntuació és 9.0
{'nom': 'Marc Vidal', 'telèfon': '612443322', 'antiguitat': 6, 'català': 3, 'excel': 3, 'títol': 3}
La teva puntuació és 18.0
{'nom': 'Júlia Romero', 'telèfon': '677998877', 'antiguitat': 5, 'català': 3, 'excel': 3, 'títol': 2}
La teva puntuació és 15.5
{'nom': 'Pol Navarro', 'telèfon': '699554433', 'antiguitat': 4, 'català': 3, 'excel': 2, 'títol': 2}
La teva puntuació és 13.0
{'nom': 'David Ferrer', 'telèfon': '677665544', 'antiguitat': 2, 'català': 1, 'excel': 1, 'títol': 1}
La teva puntuació és 6.0
{'nom': 'Anna Paredes', 'telèfon': '633221144', 'antiguitat': 1, 'català': 2, 'excel': 1, 'títol': 0}
La teva puntuació és 4.5

====================================================================================================
INFORME FINAL DE CANDIDATS
====================================================================================================

# **Exercici 2: Segmentació per risc de cistella de compra**

Treballes com a **analista de dades** al departament de **Màrqueting Digital**. L'empresa vol millorar l'efectivitat de les campanyes de recuperació de cistelles de compra abandonades i necessita identificar quins clients tenen més risc d'abandonament, quin segment de comportament presenten i quin missatge publicitari és el més adequat per a cadascun.

Disposes d'un conjunt de dades amb informació bàsica de 10 clients:
*   id_client
*   nom
*   edat
*   grup_edat
*   codi_comportament

El departament de CRM ha definit manualment:

» Codis de comportament:
*   0 → Navega però no afegeix productes
*   1 → Afegeix productes però no arriba al checkout
*   2 → Arriba al checkout però no paga
*   3 → Cistella de compra abandonat fa menys de 24 h
*   4 → Cistella de compra abandonat fa més de 24 h

» Factors segons codi de comportament:
*   Codi 0 → 0.10
*   Codi 1 → 0.25
*   Codi 2 → 0.50
*   Codi 3 → 0.75
*   Codi 4 → 0.90

» Factors segons grup d'edat
*   18–25 → 1.20
*   26–40 → 1.00
*   41–60 → 0.85
*   60+ → 0.70

» Fórmula del risc final

risc_final = factor codi * factor edat

Un cop processats els clients, has de ser capaç de respondre:
*   » 1. Quins clients s'han de contactar primer en una campanya de retargeting?
*   » 2. Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents? (Per exemple: un client jove que abandona la cistella de compra fa 24 h té el mateix risc que un de més edat?)
*   » 3. Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost?
*   » 4. Quin client seria el més rendible de recuperar?

Interpretant el risc final i el segment.

# **Disseny i implementació de la solució**

## 🧠 **Algoritme inicial**

1. Processar clients:
    *   Obtenir segment, factor i missatge segons codi comportament.
    *   Obtenir factor edat.
    *   Calcular risc.
2. Mostrar dataframe amb les dades de tots els clients.
3. Mostrar respostes a les qüestions.

# **📚 Llibreries**

Importem la **llibreria pandas** per poder crear un dataframe i utilitzar els mètodes associats.

In [80]:
import pandas as pd

## **💢 Estructures de dades**

El conjunt de **dades inicial** és una llista de diccionaris. Cada diccionari conté les dades bàsiques de cada client.

In [81]:
clients = [
      {"id_client": 1, "nom": "Laura Serra", "edat": 23, "grup_edat": "18-25", "codi_comportament": 4},
      {"id_client": 2, "nom": "Marc Vidal", "edat": 35, "grup_edat": "26-40", "codi_comportament": 3},
      {"id_client": 3, "nom": "Ana López", "edat": 29, "grup_edat": "26-40", "codi_comportament": 2},
      {"id_client": 4, "nom": "Joan Riera", "edat": 19, "grup_edat": "18-25", "codi_comportament": 2},
      {"id_client": 5, "nom": "Mónica Pérez", "edat": 47, "grup_edat": "41-60", "codi_comportament": 4},
      {"id_client": 6, "nom": "Luis García", "edat": 52, "grup_edat": "41-60", "codi_comportament": 1},
      {"id_client": 7, "nom": "Pilar Sánchez", "edat": 61, "grup_edat": "60+", "codi_comportament": 3},
      {"id_client": 8, "nom": "Eva Martín", "edat": 38, "grup_edat": "26-40", "codi_comportament": 0},
      {"id_client": 9, "nom": "Diego Romero", "edat": 24, "grup_edat": "18-25", "codi_comportament": 1},
      {"id_client": 10, "nom": "Núria Costa", "edat": 33, "grup_edat": "26-40", "codi_comportament": 4}
]

Definim dos diccionaris amb les dades associades al codi comportament i al grup d'edat.

In [82]:
MAPA_COMPORTAMENT = {
    0: {"factor": 0.10, "segment": "Navegador passiu", "missatge": "Descobreix les nostres novetats que et podrien agradar!"},
    1: {"factor": 0.25, "segment": "Interès inicial", "missatge": "Encara hi ets a temps! Els teus productes t'esperen a la cistella."},
    2: {"factor": 0.50, "segment": "Abandó a checkout", "missatge": "Completa la teva comanda ara i t'enviem un codi d'enviament gratuït."},
    3: {"factor": 0.75, "segment": "Abandó recent (<24h)", "missatge": "Has oblidat alguna cosa? Finalitza la teva compra abans que s'exhaureixi l'estoc."},
    4: {"factor": 0.90, "segment": "Abandó crític (>24h)", "missatge": "T'oferim un 10% de descompte exclusiu per recuperar la teva cistella!"}
}

MAPA_EDAT = {
    "18-25": 1.20,
    "26-40": 1.00,
    "41-60": 0.85,
    "60+": 0.70
}

## 🧩 **Descomponent el problema: naixement de les funcions**

### ***♻ Re-utilització de funcions:***

*   **mostrar_dataframe(df, títol):** utilitzarem aquesta funció per mostrar en format tabular la llista de clients i les dades relacionades.

### ***✔ obtenir_valors(clau, diccionari)***

**Paràmetres:** clau i diccionari

**Operacions:** Rep una clau i accedeix a l'estructura del diccionari indicat per extreure directament les dades associades.

**Retorn:** dades associades a la clau

In [83]:
def obtenir_valors(clau, diccionari):
  #Retorna les dades associades a la clau indicada dins del diccionari
  return diccionari.get(clau)

### ***✔ calcular_risc(factor codi, factor edat)***

**Paràmetres:** factor de codi comportament i factor d'edat

**Operacions:**  Calcular: risc final = factor codi * factor edat

**Retorn:** el valor de risc final arrodonit.

In [84]:
def calcular_risc(factor_codi, factor_edat):
  #Retorna el risc calculat arrodonit a 2 decimals.
  return round(factor_codi * factor_edat , 2)

### ***✔ processar_clients(llista inicial)***

**Paràmetre:** llista de diccionaris amb les dades dels clients.

**Passos:**
1. Per cada client de la llista inicial:
    - Obtenir factor, segment i missatge segons codi comportament --> obtenir_dades()
    - Obtenir factor edat -- > obtenir_dades()
    - Calcular risc --> calcular_risc()
    - Guardar aquestes dades a un nou diccionari.
    - Afegir el nou diccionari del client amb les dades actualitzades a la llista final.

**Retorn:** la llista de clients actualitzada

In [85]:
def processar_dades(client):

  #inicialitzem un nou diccionari i hi copiem les dades actuals del client
  dades_client = {}
  dades_client = client
  #obtenim segment, missatge i factor segons codi comportament i els guardem al nou diccionari
  dades_comportament  = obtenir_valors(client['codi_comportament'], MAPA_COMPORTAMENT)
  dades_client ['segment'] = dades_comportament ['segment']
  dades_client ['missatge'] = dades_comportament ['missatge']
  dades_client ['factor_codi'] = dades_comportament ['factor']
  #obtenim factor segons grup d'edat i el guardem al nou diccionari
  dades_client ['factor_edat'] = obtenir_valors(client['grup_edat'], MAPA_EDAT)
  #calculem risc i el guardem al nou diccionari
  dades_client ['risc_final'] = calcular_risc(dades_client ['factor_codi'], dades_client ['factor_edat'] )

  #retornem diccionari final amb les dades actualitzades
  return dades_client

In [86]:
def convertir_llista(llista_inicial):
  #Retorna una llista de diccionaris. Cada diccionari conté les dades dels elements de la llista inicial actualitzades
  llista_final = []
  for element in llista_inicial:
    llista_final.append(processar_dades(element))
  df = pd.DataFrame(llista_final)
  return df

### ***✔ mostrar_respostes(dataframe)***

**Paràmetre:** dataframe amb les dades dels clients.

**Tasques:**
1. Processar les dades per respondre:
*   » 1. Quins clients s'han de contactar primer en una campanya de retargeting?
Trobar els 3 clients que tinguin risc més alt.
*   » 2. Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents? (Per exemple: un client jove que abandona la cistella de compra fa 24 h té el mateix risc que un de més edat?)
El factor edat disminueix el risc

*   » 3. Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost?
Trobar els 3 clients amb risc més baix.
*   » 4. Quin client seria el més rendible de recuperar?

2. Mostrar respostes.

In [87]:
def mostrar_respostes(df):
    #Mostrar títol
    print("\n" + "="*50)
    print("INFORMES I CONCLUSIONS ESTRATÈGIQUES DE MÀRKETING")
    print("="*50)

    print ("RESPOSTES")
    print ("1. Quins clients s'han de contactar primer ?")
    print ("2. Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents?")
    print ("3. Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost?")
    print ("4. Quin client seria el més rendible de recuperar?")

    # 1. Prioritat de contacte (Ordenat per Risc Final de més a menys)
    print("\n» 1. Quins clients s'han de contactar primer en una campanya de retargeting?")
    print("Seleccionem els 3 clients amb risc més alt.")
    df_ordenat = df.sort_values(by="risc_final", ascending=False)
    primers_contactes = df_ordenat.head(3)[["nom", "risc_final"]]
    display(primers_contactes)


    # 2. Anàlisi d'impacte edat amb igual comportament
    print("\n» 2. Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents?")
    print("  • Els clients joves (18-25) tenen un factor multiplicador de risc més alt (1.20).")
    print("  • Exemple pràctic del dataset: Laura Serra (23 anys) i Núria Costa (33 anys) tenen")
    print("    el mateix codi 4, però la Laura té un risc final superior (1.08) que la Núria (0.90)")
    print("    perquè el segment jove tendeix a una volatilitat o abandonament digital més alt.")
    df_ordenat = df.sort_values(by=['codi_comportament','edat'], ascending=[True, True])
    df_ordenat.style.hide(axis='index')
    display(df_ordenat)

    # 3. Baix interès (Filtre per risc molt baix, ex: risc < 0.20)
    desestimats = df[df["risc_final"] < 0.20][["nom", "risc_final", "segment"]]
    print("\n» 3. Quins clients presenten tan poc interès que NO val la pena invertir-hi pressupost?")
    for _, row in desestimats.iterrows():
        print(f"  • {row['nom']} (Risc: {row['risc_final']} | Segment: {row['segment']})")

    # 4. Client més rendible de recuperar
    # Màxim risc d'abandonament alt unit a interès real (Checkout o Cistella recent sense deixar passar massa temps)
    # Segons la matriu, el client amb més risc i cistella activa és Laura Serra (1.08) i en segment recent Marc Vidal (0.75).
    mes_rendible = df_ordenat.iloc[0]
    print("\n» 4. Quin client seria el més rendible de recuperar?")
    print(f"  • {mes_rendible['nom']}. Té el risc final més alt de tot el dataset ({mes_rendible['risc_final']})")
    print(f"    dins del segment '{mes_rendible['segment']}'. En recuperar-la, evitem la pèrdua del client")
    print(f"    amb més probabilitats de refredar-se definitivament.")

### ***✔ main_marketing(clients)***

**Paràmetre:** llista de diccionaris amb les dades dels candidats.

**Tasques:**
1. Processar clients --> processar_clients()

2. Mostrar les dades dels clients --> mostrar_dataframe()

3. Mostrar respostes --> mostrar_respostes()

In [88]:
def main_marketing(clients):
    df_clients = convertir_llista(clients)
    mostrar_dataframe(df_clients, "DATASET FINAL DE CLIENTS SEGMENTATS")
    mostrar_respostes(df_clients)

In [89]:

main_marketing(clients)

====================================================================================================
DATASET FINAL DE CLIENTS SEGMENTATS
====================================================================================================

==================================================
INFORMES I CONCLUSIONS ESTRATÈGIQUES DE MÀRKETING
==================================================
RESPOSTES
1. Quins clients s'han de contactar primer ?
2. Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents?
3. Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost?
4. Quin client seria el més rendible de recuperar?

» 1. Quins clients s'han de contactar primer en una campanya de retargeting?
Seleccionem els 3 clients amb risc més alt.

            nom  risc_final
0   Laura Serra        1.08
9   Núria Costa        0.90
4  Mónica Pérez        0.77

» 2. Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents?
  • Els clients joves (18-25) tenen un factor multiplicador de risc més alt (1.20).
  • Exemple pràctic del dataset: Laura Serra (23 anys) i Núria Costa (33 anys) tenen
    el mateix codi 4, però la Laura té un risc final superior (1.08) que la Núria (0.90)
    perquè el segment jove tendeix a una volatilitat o abandonament digital més alt.

,id_client,nom,edat,grup_edat,codi_comportament,segment,missatge,factor_codi,factor_edat,risc_final
7,8,Eva Martín,38,26-40,0,Navegador passiu,Descobreix les nostres novetats que et podrien...,0.10,1.00,0.10
8,9,Diego Romero,24,18-25,1,Interès inicial,Encara hi ets a temps! Els teus productes t'es...,0.25,1.20,0.30
5,6,Luis García,52,41-60,1,Interès inicial,Encara hi ets a temps! Els teus productes t'es...,0.25,0.85,0.21
3,4,Joan Riera,19,18-25,2,Abandó a checkout,Completa la teva comanda ara i t'enviem un cod...,0.50,1.20,0.60
2,3,Ana López,29,26-40,2,Abandó a checkout,Completa la teva comanda ara i t'enviem un cod...,0.50,1.00,0.50
1,2,Marc Vidal,35,26-40,3,Abandó recent (<24h),Has oblidat alguna cosa? Finalitza la teva com...,0.75,1.00,0.75
6,7,Pilar Sánchez,61,60+,3,Abandó recent (<24h),Has oblidat alguna cosa? Finalitza la teva com...,0.75,0.70,0.52
0,1,Laura Serra,23,18-25,4,Abandó crític (>24h),T'oferim un 10% de descompte exclusiu per recu...,0.90,1.20,1.08
9,10,Núria Costa,33,26-40,4,Abandó crític (>24h),T'oferim un 10% de descompte exclusiu per recu...,0.90,1.00,0.90
4,5,Mónica Pérez,47,41-60,4,Abandó crític (>24h),T'oferim un 10% de descompte exclusiu per recu...,0.90,0.85,0.77

» 3. Quins clients presenten tan poc interès que NO val la pena invertir-hi pressupost?
  • Eva Martín (Risc: 0.1 | Segment: Navegador passiu)

» 4. Quin client seria el més rendible de recuperar?
  • Eva Martín. Té el risc final més alt de tot el dataset (0.1)
    dins del segment 'Navegador passiu'. En recuperar-la, evitem la pèrdua del client
    amb més probabilitats de refredar-se definitivament.

# **Nivell 2**

# **Exercici 1: Gestió de risc i priorització de pacients**

Treballes com a **analista de dades** en un **centre mèdic** especialitzat. Diversos pacients han enviat els seus símptomes a través d'un formulari online, però les dades arriben en un format desordenat i poc estructurat, i l'equip mèdic necessita que els organitzis per poder prioritzar l'ordre d'atenció segons la gravetat.

🎯 **Objectius**

L'objectiu és transformar aquestes dades en informació útil per als metges. A partir dels registres en brut, has de:

» Convertir cada string en una estructura neta (diccionari o similar).

» Separar i normalitzar la llista de símptomes:
*   minúscules
*   eliminar espais
*   dividir correctament per comes

» Assignar un risc a cada símptoma utilitzant el diccionari nivells_risc.

» Calcular el risc total de cada pacient sumant els valors.

» Ordenar els pacients de major a menor risc per determinar la prioritat d'atenció.

# **Disseny i implementació de la solució**

## 🧠 **Algoritme inicial**

1. **Convertir la llista inicial** de strings en un dataframe:
    *   Separar la cadena per | i obtenir nom, edat, llista símptomes
    *   Separar la llista de símptomes per ,
    *   **Netejar símptomes**:
        *   Convertir a mínuscules.
        *   Netejar espais inicials i finals
        *   Posar _ enlloc d'espais.
    *   **Calcular risc** per cada client sumant els riscos associats a cada símptoma.
2. **Ordenar** la llista de pacients pel risc total de forma descendent.
3. **Mostrar** la llista ordenada de pacients.

# **📚 Llibreries**

Importem la **llibreria pandas** per poder crear un dataframe i utilitzar els mètodes associats.

In [90]:
import pandas as pd

## **💢 Estructures de dades**

El conjunt de **dades inicial** és una llista de cadenes amb la informació de cada pacient.

In [91]:
pacients = [
    "Maria|45|tos, Fiebre Alta, dolor_pecho",
    "Luis|33|dolor_cabeza,faTiga",
    "Sara|67|fiebre alta, dificultad RESPIRAR, tos",
    "Jordi|52|fatiga , tos",
    "Anna|29|fiebre alta,dolor_cabeza"
]

També disposem d'un **diccionari de nivells de risc** per símptoma:

In [92]:
nivells_risc = {
    "fiebre_alta": 3,
    "dificultad_respirar": 5,
    "dolor_pecho": 4,
    "tos": 1,
    "fatiga": 1,
    "dolor_cabeza": 1
}

A partir d'aquestes dades construïrem una **llista de diccionaris**. Cada diccionari contindrà les dades d'un pacient:

[{'nom': 'Maria', 'edat': 45, 'símptomes': ['tos', 'fiebre_alta', 'dolor_pecho'], 'risc_total': 8},

{'nom': 'Luis', 'edat': 33, 'símptomes': ['dolor_cabeza', 'fatiga'], 'risc_total': 2}, ...]

Finalment convertirem aquesta llista aen un **dataframe** per poder optimitzar la gestió i visualització de les dades.

## 🧩 **Descomponent el problema: naixement de les funcions**

### ***♻ Re-utilització de funcions:***
*   **convertir_llista(llista_inicial):** utilitzarem aquesta funció per convertir la llista inicial de pacients (strings) en un dataframe on cada fila conté les dades d'un pacient.
*   **ordenar_dataframe(df, camp, ordre):** utilitzarem aquesta funció per ordenar el dataframe per la columna de risc de forma descendent.
*   **mostrar_dataframe(df, títol):** utilitzarem aquesta funció per mostrar en format tabular la llista de pacients i les dades relacionades: símptomes i nivell de risc.

### ***✔ netejar_símptomes(llista_inicial)***

**Paràmetres:** llista de símptomes en brut

**Operacions:**
1. Per cada element de la llista:
    *   convertir a mínuscules
    *   netejar espais inicials i finals
    *   convertir espais intermitjos a _

**Retorn:** llista actualitzada de símptomes

In [93]:
def netejar_símptomes(llista_inicial):
  #Retorna

  # Inicialitzem la llista
  llista_final = []
  for símptoma in llista_inicial:
    llista_final.append(símptoma.lower().lstrip().rstrip().replace(" ", "_"))
  return llista_final

### ***✔ calcular_risc(llista_símptomes)***

**Paràmetres:** llista de símptomes

**Operacions:**
1. Per cada element de la llista:
    *   risc total = risc total + risc símptoma

**Retorn:** risc total del pacient

In [94]:
def calcular_risc (llista_símptomes):
  risc_pacient = 0
  for símptoma in llista_símptomes:
    if símptoma in nivells_risc:
      risc_pacient += nivells_risc[símptoma]
  return risc_pacient

### ***✔ processar_dades(pacient)***

**Paràmetres:** string amb les dades d'un pacient

**Operacions:**
1. Inicialitzar diccionari del pacient
2. Separar camps per |
3. Separar símptomes per , i crear llista
4. Assignar valors al diccionari amb les claus: nom, edat i símptomes

**Retorn:** diccionari amb les dades del pacient actualitzades

In [95]:
def processar_dades(pacient):
  # Transforma un string de dades brutes en un diccionari amb les dades normalitzades

  # Inicialitzem el diccionari on recollirem les dades del pacient
  dades_pacients = {}
  # Separem la cadena inicial pel separador | i obtenim una llista d'elements
  dades = pacient.split("|")
  # Creem una clau anomenada 'nom' dins del diccionari dades_pacients i li assignem el valor del primer element de la llista
  dades_pacients['nom'] = dades[0]
  # Creem una clau anomenada 'edat' dins del diccionari dades_pacients i li assignem el valor del segon element de la llista convertit a enter
  dades_pacients['edat'] = int(dades[1])
  dades_pacients['símptomes'] = netejar_símptomes(dades[2].split(","))
  dades_pacients['risc_total'] = calcular_risc(dades_pacients['símptomes'])

  return dades_pacients

In [96]:
def main_centre_mèdic(llista_pacients):
  df_pacients = convertir_llista(llista_pacients)
  ordenar_dataframe(df_pacients, 'risc_total', False)
  mostrar_dataframe (df_pacients, "DATASET FINAL DE PACIENTS")

In [97]:
# Cridem la funció principal. Li passem com a argument la llista bruta de pacients.
main_centre_mèdic(pacients)

====================================================================================================
DATASET FINAL DE PACIENTS
====================================================================================================

# **Exercici 2: Classificació de clients d'assegurances**

Treballes com a **analista de dades** en una **companyia asseguradora**.
L'empresa vol calcular el risc dels clients, el preu estimat de la pòlissa i la probabilitat de frau, utilitzant un **codi de comportament** que ha estat generat per un model intern.
Tens una llista de clients i un diccionari amb les categories del sistema.

El **preu final** s'ha de calcular amb la fórmula:  preu_final = preu_base * (1 + edat/100)

🎯 **Objectius**

» **Classificar** cada client utilitzant nivells_seguro (sense if/elif).

» **Afegir**:

  *   La categoria
  *   El preu base
  *   La probabilitat de frau


» **Calcular el preu final** de la pòlissa amb la fórmula donada.

» **Crear un DataFrame** o diccionari amb la informació final.

» **Ordenar** els clients:
  *   Per probabilitat de frau (descendent).
  *   Per preu final.

✅ **Resultat esperat**

» Un **DataFrame** o un diccionari amb:
  *   Nom
  *   Edat
  *   Categoria
  *   Preu_base
  *   Preu_final
  *   Probabilitat_frau

» Un apartat d'**anàlisi** on s'indiqui:
  *   Quin client té més probabilitat de frau
  *   Quin té el preu final més alt
  *   Qui seria prioritari de revisar manualment

# **Disseny i implementació de la solució**

## 🧠 **Algoritme inicial**

1. Afegir categoria, preu base i probabilitat de frau al diccionari de cada client a partir del codi de cada client.
2. Calcular preu final i afegir al diccionari de cada client.
3. Crear dataframe amb la informació de tots els clients.
4. Ordenar i mostrar el dataframe.
5. Anàlisi.

# **📚 Llibreries**

Importem la **llibreria pandas** per poder crear un dataframe i utilitzar els mètodes associats.

In [42]:
import pandas as pd

## **💢 Estructures de dades**

El conjunt de **dades inicial** és una llista de diccionaris. Cada diccionari conté les dades bàsiques de cada client: nom, edat i codi de comportament.

In [43]:
clients = [
    {"nom": "Ana", "edat": 42, "codi": 0},
    {"nom": "Carlos", "edat": 30, "codi": 2},
    {"nom": "Isabel", "edat": 55, "codi": 3},
    {"nom": "Jorge", "edat": 40, "codi": 1},
    {"nom": "Marta", "edat": 28, "codi": 0}
]

També disposem d'un **diccionari de categories** on la clau és el codi de comportament de cada client i el valor és un diccionari amb les dades associades: categoria, preu base de la pòlissa i probabilitat de frau.

In [44]:
nivells_seguro = {
    0: {"categoria": "Baix risc", "preu_base": 120, "fraude": 0.01},
    1: {"categoria": "Risc mitjà", "preu_base": 200, "fraude": 0.05},
    2: {"categoria": "Risc alt", "preu_base": 350, "fraude": 0.15},
    3: {"categoria": "Risc crític", "preu_base": 500, "fraude": 0.30}
}

## 🧩 **Descomponent el problema: naixement de les funcions**

### ***♻ Re-utilització de funcions:***

*   **obtenir_valors(clau, diccionari):** utilitzarem aquesta funció per extreure les dades del diccionari nivells_seguro a partir del codi de comportament de cada client.
*   **convertir_llista(llista_inicial):** utilitzarem aquesta funció per convertir la llista inicial de clients en un dataframe on cada fila conté les dades actualitzades d'un client.
*   **ordenar_dataframe(df, camp, ordre):** utilitzarem aquesta funció per ordenar el dataframe per la columna de probabilitat i després per la columna de preu.
*   **mostrar_dataframe(df, títol):** utilitzarem aquesta funció per mostrar en format tabular la llista de clients i les dades relacionades.

### ***✔ afegir_dades(llista inicial)***

**Paràmetres:** llista de clients inicial

**Operacions:**
1. Per cada client de la llista inicial:
    *   obtenir dades a partir del codi de comportament:
          *   categoria
          *   preu base
          *   probabilitat de frau
    *   calcular el preu final
    *   afegir dades a la llista final

**Retorn:** diccionari final actualitzat

In [45]:
def processar_dades(client):
  # Rep diccionari i retorna un diccionari que conté les dades dels clients actualitzades

  dades = obtenir_valors(client['codi'], nivells_seguro)
  client['categoria'] = dades['categoria']
  client['preu_base'] = dades['preu_base']
  client['probabilitat_frau'] = dades['fraude']
  client['preu_final'] = round(client['preu_base'] * (1 + client['edat']/100),2)

  return client

» Un apartat d'anàlisi on s'indiqui:

*   Quin client té més probabilitat de frau
*   Quin té el preu final més alt
*   Qui seria prioritari de revisar manualment

In [46]:
def analisi(df):
  print("\n" + "="*100)
  print("ANÀLISI")
  print("="*100)
  print("Client amb més probabilitat de frau: " + df[df['probabilitat_frau'] == df['probabilitat_frau'].max()]['nom'].to_string(index=False))
  print("Client amb preu final més alt: " + df[df['preu_final'] == df['preu_final'].max()]['nom'].to_string(index=False))
  print("Client prioritari de revisar manualment: ")

In [47]:
def main_assegurances(clients):
  #
  df_clients = convertir_llista(clients)
  ordenar_dataframe(df_clients, 'probabilitat_frau', False)
  mostrar_dataframe (df_clients, "DATASET FINAL DE CLIENTS ORDENAT PER PROBABILITAT DE FRAU")
  ordenar_dataframe(df_clients, 'preu_final', True)
  mostrar_dataframe (df_clients, "DATASET FINAL DE CLIENTS ORDENAT PER PREU FINAL")
  analisi(df_clients)

In [48]:
main_assegurances(clients)

====================================================================================================
DATASET FINAL DE CLIENTS ORDENAT PER PROBABILITAT DE FRAU
====================================================================================================

====================================================================================================
DATASET FINAL DE CLIENTS ORDENAT PER PREU FINAL
====================================================================================================

====================================================================================================
ANÀLISI
====================================================================================================
Client amb més probabilitat de frau: Isabel
Client amb preu final més alt: Isabel
Client prioritari de revisar manualment:

# **Nivell 3**

# **Exercici 1: Generador de contrasenyes segures**

Ets **analista de dades** dins el **departament de Ciberseguretat** d'una empresa tecnològica. S'ha detectat que la majoria de treballadors continuen utilitzant contrasenyes molt dèbils com “Asdf1234”, dates d'aniversari o combinacions fàcils d'endevinar. Per aquest motiu, el responsable del departament t'ha demanat desenvolupar un generador de contrasenyes segures, totalment parametritzable i modular.

📝 **Requisits del generador**

Has de crear una funció principal i totes les subfuncions necessàries per:

» Generar contrasenyes de longitud variable.

» Decidir si han d'incloure:

*   Majúscules
*   Minúscules
*   Números
*   Signes especials

» Assegurar-te que com a mínim apareix un caràcter de cada tipus seleccionat.

» Aleatoritzar completament la contrasenya.

» Retornar la contrasenya generada.

La funció principal del generador ha de tenir valors per defecte, exactament els següents:
*   Majúscules = True
*   Minúscules = True
*   Números = True
*   Signes = False

Aquests paràmetres són obligatoris i formen part del disseny del sistema.

# **Disseny i implementació de la solució**

## 🧠 **Algoritme inicial**

1. Demanar longitud i paràmetres per la creació de la contrassenya.
2. Crear llista amb conjunts de caràcters possibles en funció dels paràmetres:
    *   Majúscules = True:
        *   Majúscules: chr(65) - chr(90).
        *   escollir aleatoriament una majúscula.
        *   afegir majúscules a la llista de caràcters possibles.
    *   Minúscules = True:
        *   Minúscules: chr(97) - chr(122).
        *   escollir aleatoriament una minúscula.
        *   afegir minúscules a la llista de caràcters possibles.
    *   Números = True:
        *   Números: chr(48) - chr(57).
        *   escollir aleatoriament un número.
        *   afegir números a la llista de caràcters possibles.
    *   Signes especials = True:
        *   Signes especials: 33-47, 58-64, 91-96, 123-126.
        *   escollir aleatoriament un signe.
        *   afegir signes a la llista de caràcters possibles.
3. Escollir aleatoriament n caràcters de la llista de caràcters possibles.
    n = longitud demanada - caràcters obligatoris segons els tipus demanats
4. Barrejar tots el caràctes obtinguts.
5. Mostrar la contrassenya generada.

# **📚 Llibreries**

Importem la llibreria **numpy** per poder utilitzar les funcions del mòdul **random**. Utilitzarem:

*   random.choice (llista) --> escull de forma aleatoria un element de la llista
*   random.shuffle (llista) --> barreja de forma aleatoria els elements de la llista

In [1]:
import numpy as np

## **💢 Estructures de dades**

## 🧩 **Descomponent el problema: naixement de les funcions**

In [2]:
def obtenir_paràmetres():
  global majúscules, minúscules, números, signes
  longitud = int(input ("Introdueix la longitud de la contrassenya: "))
  majúscules = True if (input ("Inclou majúscules? (S/N): ") == 'S') else False
  minúscules = True if (input ("Inclou minúscules? (S/N): ") == 'S') else False
  números = True if (input ("Inclou números? (S/N): ") == 'S') else False
  signes = True if (input ("Inclou signes? (S/N): ") == 'S') else False
  return longitud

### ***✔ caràcters_ascii(codi_ini, codi_fin)***

**Paràmetre:** codi ascii inicial i codi ascii final

**Passos:**

1. Des del codi inicial fins al codi final:
    *   caràcter = chr(codi).
    *   afegir caràcter a la llista final.

**Retorn:** la llista de caràcters associats als codis rebuts.

In [3]:
def caràcters_ascii(codi_ini, codi_fin):
  #Retorna una llista de caràcters associats als codis ascii rebuts
  llista_final = []
  for codi in range(codi_ini, codi_fin+1):
    llista_final.append(chr(codi))
  return llista_final

### ***✔ definir_llista(majus, minus, num, signes)***

**Paràmetres:** valors booleans indicant si la llista ha de contenir majúscules, minúscules, números i signes.

**Passos:**

1. Crear llista amb conjunts de caràcters possibles en funció dels paràmetres:
    *   Majúscules = True:
        *   Majúscules: chr(65) - chr(90).
        *   escollir aleatoriament una majúscula.
        *   afegir majúscules a la llista de caràcters possibles.
    *   Minúscules = True:
        *   Minúscules: chr(97) - chr(122).
        *   escollir aleatoriament una minúscula.
        *   afegir minúscules a la llista de caràcters possibles.
    *   Números = True:
        *   Números: chr(48) - chr(57).
        *   escollir aleatoriament un número.
        *   afegir números a la llista de caràcters possibles.
    *   Signes especials = True:
        *   Signes especials: 33-47, 58-64, 91-96, 123-126.
        *   escollir aleatoriament un signe.
        *   afegir signes a la llista de caràcters possibles.

**Retorn:** la llista final amb tots els caràcters possibles per crear la contrassenya.

In [4]:
def definir_llista (majus, minus, num, signes):
  llista_final = []
  llista_cars_obligatoris = []
  if majus:
    llista_cars_obligatoris += np.random.choice(caràcters_ascii(65, 90))
    llista_final += caràcters_ascii(65, 90)
  if minus:
    llista_cars_obligatoris += np.random.choice(caràcters_ascii(97, 122))
    llista_final += caràcters_ascii(97, 122)
  if num:
    llista_cars_obligatoris += np.random.choice(caràcters_ascii(48, 57))
    llista_final += caràcters_ascii(48, 57)
  if signes:
    llista_cars_obligatoris += np.random.choice(caràcters_ascii(33, 47) + caràcters_ascii(58, 64) + caràcters_ascii(91, 96) + caràcters_ascii(123, 126))
    llista_final += (caràcters_ascii(33, 47) + caràcters_ascii(58, 64) + caràcters_ascii(91, 96) + caràcters_ascii(123, 126))
  return llista_final, llista_cars_obligatoris

### ***✔ crear_contrassenya(longitud, majúscules, minúscules, números, signes)***

**Paràmetre:** longitud de la contrassenya, valors booleans indicant si la contrassenya ha de contenir majúscules, minúscules, números i signes.

**Passos:**

1. Crear llista amb conjunts de caràcters possibles en funció dels paràmetres:
2. Crear llista amb caràcters obligatoris segons els paràmetres.
2. Escollir aleatoriament n caràcters de la llista de caràcters possibles.
    n = longitud demanada - caràcters obligatoris segons els tipus demanats
3. Barrejar tots el caràctes obtinguts.

**Retorn:** contrassenya que compleix els requeriments indicats en els paràmetres.

In [5]:
def crear_contrassenya (longitud, majúscules, minúscules, números, signes ):
  llista_final, llista_cars_obligatoris = definir_llista(majúscules, minúscules, números, signes)
  contrassenya = []
  for i in range(longitud -len(llista_cars_obligatoris)):
    contrassenya += np.random.choice(llista_final)
  print (contrassenya)
  print (llista_cars_obligatoris)
  contrassenya = llista_cars_obligatoris + contrassenya
  np.random.shuffle(contrassenya)
  contrassenya_final = "".join(contrassenya)
  return contrassenya_final

In [6]:
def main_contrassenya():
  longitud = obtenir_paràmetres()
  contrassenya = crear_contrassenya(longitud, majúscules, minúscules, números, signes)
  print (contrassenya)

In [7]:
majúscules = True
minúscules = True
números =  True
signes = False
main_contrassenya()

Introdueix la longitud de la contrassenya: 15
Inclou majúscules? (S/N): S
Inclou minúscules? (S/N): S
Inclou números? (S/N): S
Inclou signes? (S/N): S
['x', 'Y', 'V', 'P', '[', 'T', 'H', 'Z', '$', 'W', 'i']
['B', 't', '0', '#']
THxB#PWtY[0VZ$i

# **Exercici 2: Processament automàtic de dades esportives**

Ara formes part d'un **equip d'analítica** dins una **organització esportiva** que gestiona dades de la lliga catalana. La teva companya de feina vol automatitzar la lectura del seu arxiu històric de resultats i extreure les estadístiques més importants. T'ha demanat fer un petit sistema en Python que processi el fitxer 📄 "historic partits.txt"

🎯 **Objectius**

Mitjançant un codi modular, clar i documentat, el teu programa ha de calcular:

» 1.Quin equip és el més golejador.

» 2.Quin és el més golejat.

» 3.El nombre total de gols que ha fet cada equip.

» 4.La classificació final ordenada per punts on cada victòria suma 3 pts, cada empat 1 pts y cada derrota 0 pts.

En aquest nivell no es dona cap funció. Ets tu qui ha de dissenyar un flux complet. El codi ha de reflectir una bona organització interna.

✅ **Resultat esperat**

Un DataFrame o diccionari final i el resultat de l'anàlisi indicat.

# **Disseny i implementació de la solució**

## 🧠 **Algoritme inicial**

1. **Llegir dades** del fitxer i obtenir per cada partit: equip local, gols local, equip visitant, gols visitant.
2. Per cada partit :    -->**processar dades**
    *   afegir equip local a la llista final:
        *   sumar gols a favor
        *   sumar gols en contra
        *   sumar a partits guanyats, empatats o perduts.
        *   actualitzar punts
    *   afegir equip visitant a la llista final:
        *   sumar gols a favor
        *   sumar gols en contra
        *   sumar a partits guanyats, empatats o perduts.
        *   actualitzar punts
4. **Ordenar** la llista d'equips per punts
5. **Mostrar** la llista ordenada
6. Mostrar:   --> **anàlisi**
    *   equip més golejador
    *   equip més golejat
    *   classificació final

# **📚 Llibreries**

Importem la **llibreria pandas** per poder crear un dataframe i utilitzar els mètodes associats.

In [18]:
import pandas as pd

## **💢 Estructures de dades**

El conjunt de dades inicial és un **fitxer text**. Cada línia del fitxer conté informació d'un partit de la lliga catalana amb la següent estructura::

      Manlleu	0-1	Granollers

      Vilafranca	4-5	Terrassa

      Olot	5-0	Granollers

      Vilafranca	5-5	Manlleu

      ...

Per poder treballar amb aquestes dades les guardarem en una **llista de partits**. Cada element de la llista serà un diccionari que contindrà l'informació d'un partit: equip local, equip visitant, gols de cada equip:

      [{'equip_local': 'Manlleu', 'equip_visitant': 'Granollers', 'gols_local': 0, 'gols_visitant': 1},

      {'equip_local': 'Vilafranca', 'equip_visitant': 'Terrassa', 'gols_local': 4, 'gols_visitant': 5}, ...]

Un cop processades les dades obtindrem un **diccionari d'equips**. Les claus del diccionari seran els noms dels equips i els valors seran diccionaris amb les dades de cada equip:

      {'Manlleu': {'gols_a_favor': 106, 'gols_en_contra': 118, 'partits_guanyats': 16, 'partits_empatats': 9, 'partits_perduts': 18, 'punts': 57},
      'Granollers': {'gols_a_favor': 122, 'gols_en_contra': 117, 'partits_guanyats': 21, 'partits_empatats': 4, 'partits_perduts': 24, 'punts': 67}, ...}

Finalment convertirem aquest diccionari a **dataframe** per poder mostrar i analitzar millor la informació.

## 🧩 **Descomponent el problema: naixement de les funcions**

### ***♻ Re-utilització de funcions:***

*   **ordenar_dataframe(df, camp, ordre):** utilitzarem aquesta funció per ordenar el dataframe d'equips per la columna de punts de forma descendent.

*   **mostrar_dataframe(df, títol):** utilitzarem aquesta funció per mostrar en format tabular la llista d'equips i les dades relacionades.

### ***✔ llegir_fitxer(url)***

**Paràmetre:** url del fitxer

**Passos:**

1. Llegir fitxer i guardar dades a dataframe amb les següents columnes:   
    *   equip local
    *   resultat
    *   equip visitant
2. Separar columna resultat i obtenir:
    *   gols equip local
    *   gols equip visitant
3. Esborrar columna resultat
4. Convertir gols a integer
5. Convertir dataframe a llista de diccionaris. Cada diccionari conté les dades d'un partit.

**Retorn:** la llista de partits amb les seves dades: equip local, gols local, equip visitant, gols visitant.

In [19]:
def llegir_fitxer(url):
  #Retorna una llista de partits amb les seves dades

  # Llegim fitxer text que es troba a l'adreça url, camps separats per tabulador i  sense capçalera.
  #obtenim dataframe i assignem noms a les columnes
  columnes = ["equip_local", "resultat", "equip_visitant"]
  df = pd.read_csv(url, sep = "\t", header = None, names = columnes)

  # Separem la columna 'resultat' pel guió '-' en dues columnes noves
  gols = df['resultat'].str.split('-', expand=True)
  df['gols_local'] = gols[0]
  df['gols_visitant'] = gols[1]

  # Eliminem la columna 'resultat' original
  df.drop(columns=['resultat'], inplace=True)

  # Convertim les columnes de gols a números enters
  df['gols_local'] = df['gols_local'].astype(int)
  df['gols_visitant'] = df['gols_visitant'].astype(int)

  # Convertim cada fila del dataFrame en un diccionari on les claus són els noms de les columnes.
  llista_final = df.to_dict(orient = 'records')

  return llista_final

### ***✔ processar_dades(llista_inicial)***

**Paràmetre:** llista inicial amb les dades dels partits

**Passos:**
1. Inicialitzar diccionari d'equips.
2. Per cada partit :
    *   Si no existeixen crear clau al diccionari per equip local i equip visitant amb valors a 0.
    *   actualitzar gols equip local:
        *   gols a favor = gols a favor + gols local partit
        *   gols en contra = gols en contra + gols visitant partit
    *   actualitzar gols equip visitant:
        *   gols a favor = gols a favor + gols visitant partit
        *   gols en contra = gols en contra + gols local partit
    *   si gols local > gols visitant aleshores:
        *   guanyats local = guanyats local + 1
        *   perduts visitant = perduts visitant + 1
        *   punts local = punts local + 3
    *   si gols local < gols visitant aleshores:
        *   guanyats visitant = guanyats visitant + 1
        *   perduts local = perduts local + 1
        *   punts visitant = punts visitant + 3
    *   si gols local = gols visitant aleshores:
        *   empatats visitant = empatats visitant + 1
        *   empatats local = empatats local + 1
        *   punts visitant = punts visitant + 1
        *   punts local = punts local + 1

**Retorn:** el diccionari d'equips amb les seves dades: gols a favor, gols en contra, partits guanyats, partits empatats, partits perduts i punts.

In [20]:
def processar_dades(llista_partits):
  # Retorna un diccionari d'equips amb les seves dades. Les claus del diccionari són els noms dels equips.
  # Els valors del diccionari són diccionaris amb les dades de cada equip.

  # Inicialitzem el diccionari d'equips
  dict_equips = {}
  # Recorrem la llista de partits i anem construint el diccionari d'equips
  for partit in llista_partits:
    # Obtenim nom equip local i nom equip visitant
    equip_local = partit['equip_local']
    equip_visitant = partit['equip_visitant']

    # Si no existeixen afegim al diccionari equips obtinguts amb valors inicials a 0
    if equip_local not in dict_equips:
      dict_equips[equip_local] = {
          'gols_a_favor': 0,
          'gols_en_contra': 0,
          'partits_guanyats': 0,
          'partits_empatats': 0,
          'partits_perduts': 0,
          'punts': 0
      }
    if equip_visitant not in dict_equips:
      dict_equips[equip_visitant] = {
          'gols_a_favor': 0,
          'gols_en_contra': 0,
          'partits_guanyats': 0,
          'partits_empatats': 0,
          'partits_perduts': 0,
          'punts': 0
      }

    # Actualitzem gols a favor i en contra equip local
    dict_equips[equip_local]['gols_a_favor'] += partit['gols_local']
    dict_equips[equip_local]['gols_en_contra'] += partit['gols_visitant']

    # Actualitzem gols a favor i en contra equip visitant
    dict_equips[equip_visitant]['gols_a_favor'] += partit['gols_visitant']
    dict_equips[equip_visitant]['gols_en_contra'] += partit['gols_local']

    # Actualitzem partits guanyats, empatats, perduts i punts equip local i visitant
    if partit['gols_local'] > partit['gols_visitant']:
      dict_equips[equip_local]['partits_guanyats'] += 1
      dict_equips[equip_local]['punts'] += 3
      dict_equips[equip_visitant]['partits_perduts'] += 1
    elif partit['gols_local'] < partit['gols_visitant']:
      dict_equips[equip_local]['partits_perduts'] += 1
      dict_equips[equip_visitant]['partits_guanyats'] += 1
      dict_equips[equip_visitant]['punts'] += 3
    else:
      dict_equips[equip_local]['partits_empatats'] += 1
      dict_equips[equip_local]['punts'] += 1
      dict_equips[equip_visitant]['partits_empatats'] += 1
      dict_equips[equip_visitant]['punts'] += 1

  return dict_equips

### ***✔ convertir_dict_a_dataframe(diccionari, índex)***

**Paràmetres:** diccionari i nom de la clau del diccionari

**Passos:**

1. crear el dataframe a partir del diccionari(índex=claus diccionari)
2. convertir índex  a columna normal

**Retorn:** el dataframe creat.

In [21]:
def convertir_dict_a_dataframe(dict, nom_index):
  # Retorna el dataframe creat a partir del diccionari

  # Crear dataframe amb índex = claus del diccionari
  df = pd.DataFrame.from_dict(dict, orient='index')
  # Assignar nom a la columna de l'índex
  df.index.name = nom_index
  # Convertir índex en una columna i crear índex numèric
  df = df.reset_index()

  return df

### ***✔ analisi(dataframe)***

**Paràmetres:** dataframe amb les dades que volem analitzar

**Passos:**

Calcular i mostrar:
1. Equip més golejador: equip amb el màxim de gols a favor.
2. Equip més golejat: equip amb el màxim de gols en contra.
3. Classificació final: llista d'equpis ordenada per punts descendent

In [24]:
def analisi(df):
  print("\n" + "="*100)
  print("ANÀLISI")
  print("="*100)
  print("Equip més golejador: " + df[df['gols_a_favor'] == df['gols_a_favor'].max()]['Equip'].to_string(index=False))
  print("Equip més golejat: " + df[df['gols_en_contra'] == df['gols_en_contra'].max()]['Equip'].to_string(index=False))
  print("Classificació final: ")
  posicio = 1
  for _, row in df.iterrows():
        print(f"   {posicio}.{row['Equip']} ")
        posicio += 1

In [29]:
def main_partits ():
  llista_partits = llegir_fitxer ("https://raw.githubusercontent.com/roser740/Data-Analytics/refs/heads/main/TASQUES%20S7/historic%20partits.txt")
  equips = processar_dades(llista_partits)
  df_equips = convertir_dict_a_dataframe(equips, 'Equip')
  ordenar_dataframe(df_equips, 'punts', False)
  mostrar_dataframe (df_equips, "DATASET FINAL D'EQUIPS ORDENAT PER PUNTS")
  analisi(df_equips)

In [30]:
main_partits()

====================================================================================================
DATASET FINAL D'EQUIPS ORDENAT PER PUNTS
====================================================================================================

====================================================================================================
ANÀLISI
====================================================================================================
Equip més golejador: Figueres
Equip més golejat: Vilafranca
Classificació final:
   1.Girona FC
   2.Llagostera
   3.Sabadell
   4.Cornellà
   5.RCD Espanyol
   6.Figueres
   7.Lleida Esportiu
   8.Terrassa
   9.FC Barcelona
   10.Vilafranca
   11.Badalona
   12.Nàstic de Tarragona
   13.Reus Deportiu
   14.Granollers
   15.Olot
   16.Sant Andreu
   17.Manlleu
   18.Cerdanyola
   19.Prat
   20.Europa